"""Bot-authored UI strings, keyed for future per-chat localization."""

import contextvars


current_language: contextvars.ContextVar[str] = contextvars.ContextVar(
    "current_language", default="ru",
)

STRINGS: dict[str, dict[str, str]] = {
    "ru": {
        'access_denied': '⛔ Доступ к Codex-боту не разрешён. Попроси владельца добавить твой Telegram ID в whitelist.txt.',
        'account_connected': 'подключён',
        'account_not_connected': 'Аккаунт Codex не подключён. Используй /login.',
        'account_plan_line': '\nПлан: {plan}',
        'account_read_error': 'Не удалось прочитать аккаунт: {error}',
        'account_summary': 'Аккаунт: {label}',
        'attachment_download_failed': 'Файл не скачан: Telegram не дал получить файл. Попробуй ещё раз или дай ссылку.',
        'attachment_get_file_failed': 'Файл не скачан: Telegram отказал в выдаче файла. Отправь его снова или дай ссылку.',
        'attachment_local_file_access': 'Файл не скачан: нет доступа к файлу локального Bot API. Проверь права сервера и бота.',
        'attachment_local_file_missing': 'Файл не скачан: локальный Bot API больше не видит этот файл. Отправь его снова или дай ссылку.',
        'attachment_local_file_not_a_file': 'Файл не скачан: путь локального Bot API не является доступным файлом. Проверь права сервера и бота.',
        'attachment_network': 'Файл не скачан: ошибка связи с Telegram. Попробуй ещё раз или дай ссылку.',
        'attachment_no_file_id': 'Файл не прочитан: Telegram не передал его идентификатор.',
        'attachment_no_file_path': 'Файл не скачан: Telegram не вернул путь к файлу. Попробуй ещё раз или дай ссылку.',
        'attachment_no_space': 'Файл не скачан: на диске нет места. Освободи место и отправь файл снова.',
        'attachment_loading': '📥 Загружаю вложение…',
        'attachment_loading_progress': '📥 Загружаю вложение ({done}/{total})…',
        'attachment_processing_error': 'Не смог обработать вложение: {error}',
        'attachment_timeout': 'Файл не скачан: Telegram слишком долго готовил файл. Попробуй ещё раз или дай ссылку.',
        'attachment_too_big': 'Файл не скачан: размер превышает разрешённый лимит. Отправь меньший файл или дай ссылку.',
        'attachment_too_big_for_cloud': 'Файл не скачан: размер файла превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API сервер в setup.sh или дай ссылку.',
        'attachment_too_big_for_cloud_sized': 'Файл не скачан: размер {size_mb} МБ превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API сервер в setup.sh или дай ссылку.',
        'attachment_voice_transcription_failed': 'Голосовое сообщение не удалось распознать и оно не прочитано.',
        'attachment_voice_unsupported': 'Голосовые сообщения не поддерживаются на этой установке.',
        'bridge_error': '⚠️ Ошибка моста. Подробности записаны в лог.',
        'codex_process_died': 'постоянный процесс Codex неожиданно завершился',
        'codex_timed_out': 'Codex остановлен по таймауту',
        'codex_unknown_error': 'Неизвестная ошибка Codex',
        'context_auto_compacted': '🗜 Контекст сессии автоматически сжат.',
        'context_fill_critical': '⚠️ Контекст заполнен на {percent}. Рекомендуется /compact или /new.',
        'context_fill_warning': '⚠️ Контекст заполнен на {percent}; скоро понадобится /compact.',
        'command_unknown': 'Неизвестная команда. Открой меню команд Telegram.',
        'language_usage': 'Использование: /language en|ru|uk|kk|de.',
        'language_command_description': 'Выбрать язык интерфейса и персоны',
        'language_changed': 'Язык переключён: {language}.',
        'language_persona_failed': 'Язык интерфейса переключён на {language}, но перевести персону не удалось: {error}',
        'context_window_exceeded': 'Контекст текущей сессии исчерпан. Используй /compact, чтобы сжать историю и продолжить, либо /new для новой сессии.',
        'compact_done': '🗜 Контекст сессии сжат. Можно продолжать.',
        'compact_failed': '🗜 Не удалось сжать контекст: {error}',
        'compact_no_session': 'Нет активной сессии для сжатия.',
        'compact_timeout': 'Сжатие контекста не завершилось за отведённое время.',
        'compact_done_short': '🗜 Контекст сессии сжат.',
        'compact_wait_for_turn': 'Сначала дождись завершения текущего хода или используй /stop.',
        'cross_delegate_accepted': 'Принято: Codex-бот запустил задачу. Результат придёт в этот же Telegram-чат от Codex-бота.',
        'cross_delegate_account_not_ready': 'Отклонено: Codex-аккаунт для этого Telegram ID не готов. Сначала заверши /login в Codex-боте.',
        'cross_delegate_already_running': 'Отклонено: уже выполняется предыдущая делегированная задача.',
        'cross_delegate_bad_chat_id': 'Отклонено: некорректный Telegram chat_id.',
        'cross_delegate_empty_text': 'Отклонено: пустой текст задачи.',
        'cross_delegate_malformed_request': 'Отклонено: повреждённый формат запроса делегации.',
        'cross_delegate_not_whitelisted': 'Отклонено: этот Telegram ID отсутствует в whitelist Codex-бота.',
        'cross_delegate_start_failed': 'Отклонено: Codex-бот не смог запустить делегированную задачу.',
        'delegate_already_running': 'Уже выполняю предыдущую делегированную задачу.',
        'delegate_effort_unavailable': 'Мощность «{effort}» недоступна для {model}.',
        'delegate_model_unavailable': 'Модель «{model}» недоступна.',
        'delegate_env_resume_conflict': 'Нельзя использовать --env вместе с --resume.',
        'delegate_resume_thread_mismatch': 'Нельзя продолжить эту делегацию: resume_thread_id не совпадает с последним делегированным тредом.',
        'delegate_settings_error': 'Не удалось проверить настройки делегации: {error}',
        'delegate_start_error': 'Не удалось запустить делегированную задачу: {error}',
        'effort_list_error': 'Не удалось получить уровни мощности: {error}',
        'effort_picker_header': '⚡ Мощность модели {model}:',
        'effort_selected': '⚡ Мощность {model}: {effort}',
        'effort_unavailable': 'Мощность «{effort}» недоступна для {model}.\n\n{picker}',
        'effort_unsupported': 'не поддерживается',
        'file_send_bad_chat_id': 'Отклонено: некорректный Telegram chat_id.',
        'file_send_bad_path_or_caption': 'Отклонено: некорректный путь или подпись.',
        'file_send_caption_too_long': 'Отклонено: подпись длиннее лимита Telegram.',
        'file_send_delivered': 'Файл «{name}» отправлен в Telegram.',
        'file_send_malformed_request': 'Отклонено: повреждённый запрос отправки файла.',
        'file_send_not_whitelisted': 'Отклонено: Telegram ID отсутствует в whitelist.',
        'file_send_outside_outbox': 'Отклонено: файл должен быть обычным файлом из CODEX_TELEGRAM_OUTBOX.',
        'file_send_rejected': 'Telegram не принял файл: {detail}',
        'file_send_too_big': 'Отклонено: файл больше {limit} байт.',
        'file_send_unconfirmed': 'Не удалось подтвердить отправку файла: ошибка связи или таймаут ({detail}). Файл не был отправлен повторно, чтобы избежать дубля.',
        'file_over_limit': 'Файл больше лимита {limit} байт.',
        'image_file_not_found': 'Файл изображения не найден.',
        'unknown_connection_error': 'неизвестная ошибка связи',
        'unknown_error_lowercase': 'неизвестная ошибка',
        'empty_placeholder': '(пусто)',
        'help_intro': 'Codex Telegram bridge. Команды доступны в меню бота.',
        'local_api_ask_hash': 'Пришли api_hash',
        'local_api_ask_id': 'Пришли api_id',
        'local_api_bad_url': 'Установщик вернул недопустимый адрес локального сервера',
        'local_api_configured_not_installed': '⚠️ Локальный сервер сконфигурирован, но не установлен на этом хосте — прогони scripts/install-local-bot-api.sh из терминала вручную.',
        'local_api_declined_restart': 'Ладно. 🔁 Перезапускаю бота, чтобы обновление вступило в силу…',
        'local_api_env_file_missing': 'Не найден {path}',
        'local_api_failure': '⚠️ Не удалось включить локальный сервер: {details}',
        'local_api_install_running': 'Установка уже идёт, дождись.',
        'local_api_installer_failed': 'Установщик завершился с кодом {code}',
        'local_api_installer_no_url': 'Установщик не сообщил адрес локального сервера',
        'local_api_missing_dependencies': 'Не хватает зависимостей сборки. Прогони scripts/install-local-bot-api.sh из терминала вручную.',
        'local_api_no_sudo_permission': '⚠️ Нет прав перезапустить сервер, нужен sudoers-грант.',
        'local_api_offer': 'Включить приём файлов до 2 ГБ через локальный Bot API сервер? Ответь Да или Нет.',
        'local_api_preparing': '⏳ Готовлю локальный Bot API сервер…',
        'local_api_ready_restarting': '✅ Готово. Перезапускаю бота…',
        'local_api_restart_failed': '⚠️ Не смог перезапустить локальный сервер: {error}',
        'local_api_restart_ineffective': '⚠️ Не смог перезапустить локальный сервер: сервис или его порт не стал активен.',
        'local_api_restart_now': '🔁 Перезапускаю бота, чтобы обновление вступило в силу…',
        'local_api_reuse_existing': '✅ Найден уже настроенный локальный сервер, пересобирать не нужно.',
        'local_api_stage_build': '⏳ Собираю локальный Bot API сервер (может занять ~15 минут)…',
        'local_api_stage_dependencies': '⏳ Проверяю зависимости сборки…',
        'local_api_stage_done': '✅ Локальный сервер собран.',
        'local_api_stage_install': '⏳ Устанавливаю сервис…',
        'local_api_switch_failed': 'Переключатель завершился с кодом {code}',
        'local_api_was_inactive_restarted': '🔧 Локальный сервер был неактивен, перезапустил.',
        'login_complete': '✅ Вход в аккаунт Codex завершён.',
        'login_complete_ask_name': '✅ Вход в аккаунт Codex завершён.\n\nКак к тебе обращаться?',
        'login_complete_first': 'Сначала заверши вход в Codex по ранее выданной ссылке.',
        'login_device_instructions': '🔐 Подключение отдельного аккаунта Codex\n\n1. Открой: {verification_url}\n2. Введи код: {user_code}\n\nТокены сохранятся только в твоём изолированном CODEX_HOME. Бот сообщит, когда вход завершится.',
        'login_failed': '❌ Вход не завершён: {error}',
        'login_owner_not_needed': 'Владелец использует основной аккаунт ~/.codex; отдельный вход не требуется.',
        'login_start_error': 'Не удалось начать вход в Codex: {error}',
        'login_unknown_error': 'неизвестная ошибка',
        'mode_usage': 'Использование: /mode read-only|workspace-write|full',
        'model_empty': 'Codex не вернул доступных моделей.',
        'model_list_error': 'Не удалось получить список моделей: {error}',
        'model_picker_empty': 'Список моделей пуст.',
        'model_picker_header': '🧠 Доступные модели:',
        'model_selected': '🧠 Модель: {model}\nМощность: {effort}',
        'model_unavailable': 'Модель «{model}» недоступна.\n\n{picker}',
        'name_remembered': '✅ Запомнил, как к тебе обращаться.',
        'new_previous_turn_finishing': 'Предыдущий ход ещё завершается; /new пока не выполнен.',
        'new_thread_reset': '🆕 Текущий Codex-тред сброшен. Следующее сообщение начнёт новый.',
        'persona_current_caption': 'Текущая персона',
        'process_agent_default_tool': 'работа агента',
        'process_agent_label': '🤖 Агент · {tool}',
        'process_agent_message_label': '💬 Ответ',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'контекст сессии сжат',
        'process_context_compaction_label': '🗜 Сжатие контекста',
        'process_dynamic_tool_default_name': 'инструмент',
        'process_error_label': '❌ Ошибка',
        'process_exit_code_fail': '❌ Код завершения',
        'process_exit_code_ok': '✅ Код завершения',
        'process_file_change_add': 'создан',
        'process_file_change_delete': 'удалён',
        'process_file_change_fallback': 'файл изменён',
        'process_file_change_label': '📝 Изменение файла',
        'process_file_change_update': 'изменён',
        'process_image_fallback': 'изображение',
        'process_image_generation_in_progress': 'изображение создаётся',
        'process_image_generation_label': '🎨 Генерация изображения',
        'process_image_view_label': '🖼 Просмотр изображения',
        'process_plan_fallback': 'план обновлён',
        'process_plan_label': '📋 План',
        'process_reasoning_label': '🧠 Размышление',
        'process_result_generic': 'результат получен',
        'process_result_label': '📤 Результат',
        'process_review_entered': 'режим проверки включён',
        'process_review_exited': 'режим проверки завершён',
        'process_review_label': '🔍 Проверка',
        'process_sleep_label': '⏳ Ожидание',
        'process_sleep_seconds': '{seconds} с',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Инструмент',
        'process_web_search_default_query': 'поиск',
        'process_web_search_find_in_page': 'ищу на странице',
        'process_web_search_label': '🔎 Поиск',
        'process_web_search_open_page': 'открываю страницу',
        'process_web_search_searching': 'ищу в интернете',
        'process_details_block': '<details><summary>🔧 Процесс ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…и ещё {hidden} шагов выше…',
        'thinking_placeholder': 'Думаю',
        'turn_codex_error': '⚠️ Ошибка Codex: {error}',
        'turn_delegation_footer': '\n\nПродолжить делегированную сессию: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nТвой session id (до делегации): `{prior_thread_id}`. Продолжить делегированную: `/resume {thread_id}`',
        'turn_no_answer': '(нет ответа — смотри процесс выше)',
        'turn_stopped': '⏹ Выполнение остановлено.',
        'turn_tokens_line': '\n\nТокены: {usage}',
        'persona_empty': 'Пустая персона не сохранена.',
        'persona_file_read_error': 'Не удалось прочитать файл персоны: {error}',
        'persona_file_type_error': 'Файл персоны должен быть текстовым UTF-8 Markdown-файлом.',
        'persona_owner_only': 'Персона доступна только владельцу в личном чате.',
        'persona_reply_prompt': 'Пришли текст персоны или UTF-8 Markdown-файл ответом на сообщение.',
        'persona_reset_done': '✅ Персона сброшена к шаблону по умолчанию.',
        'persona_updated': '✅ Персона обновлена.',
        'persona_usage': 'Использование: /persona или /persona reset',
        'restart_after_turn': '🔄 Текущий ход завершён. Перезапускаю Codex-бота…',
        'restart_complete': '✅ Перезагрузка окончена, бот готов к работе.',
        'restart_in_progress': '🔄 Уже начинаю перезапуск; сообщение пока не принято.',
        'restart_owner_only': 'Перезапуск доступен только владельцу бота.',
        'resume_ambiguous': 'Укажи однозначный id/префикс: /resume <id>',
        'resume_delegated_kind': 'делегированную ',
        'resume_not_found': 'Сессия не найдена.',
        'resume_previous_turn_finishing': 'Предыдущий ход ещё завершается; /resume пока не выполнен.',
        'resume_success': 'Продолжаю {kind}сессию {thread_id}.',
        'session_budget_exceeded': 'Бюджет этой сессии исчерпан. Начни новую через /new.',
        'session_missing_new_started': 'Прежняя сессия не найдена; начата новая сессия Codex.',
        'sessions_current_marker': ' ← текущая',
        'sessions_list': 'Последние сессии:\n{rows}',
        'sessions_none': 'не найдены',
        'status_account_unlinked': 'не подключён',
        'status_no': 'нет',
        'status_no_session': 'нет',
        'status_report': 'ℹ️ Статус\nСессия: {thread_id}\nМодель: {model}\nМощность: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nЗанят: {busy}\nАккаунт: {account_status}',
        'status_unknown': 'не определена',
        'status_yes': 'да',
        'stop_idle': 'Сейчас нечего останавливать.',
        'stop_running': '⏹ Останавливаю текущее выполнение Codex.',
        'update_failed': '❌ Обновление не удалось:\n```\n{error}\n```',
        'update_owner_only': 'Обновление доступно только владельцу бота.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Перезапуск запланирован после завершения текущего хода.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Перезапуск запланирован между ходами.',
        'update_done_default_summary': 'Обновление завершено.',
        'update_script_failed': 'update.sh завершился с кодом {code}',
        'update_start': '⬇️ Обновляю из git...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: использовано {used}% · осталось {remaining}% · сброс {reset}',
        'rate_limit_no_data': '{label}: нет данных',
        'relative_time_days_hours': 'через {days} д {hours} ч',
        'relative_time_hours_minutes': 'через {hours} ч {minutes} мин',
        'relative_time_minutes': 'через {value} мин',
        'usage_context_line': 'Context: {context}',
        'usage_context_tokens': '~{tokens} tokens',
        'usage_cost_api_equivalent': '(~${usd} эквивалент по API-тарифу)',
        'usage_cost_error': 'Стоимость: не удалось получить ({error})',
        'usage_cost_unavailable': 'Стоимость: недоступна для текущего subscription-маршрута',
        'usage_credits_line': 'Credits: {balance}',
        'usage_effort_unknown': 'не определён',
        'usage_label_cached': 'cached',
        'usage_label_in': 'in',
        'usage_label_out': 'out',
        'usage_label_reasoning': 'reasoning',
        'usage_limit_exceeded_details': '⏳ Лимит сессии Codex исчерпан: {details}. После сброса можно продолжить этот же тред.',
        'usage_limit_exceeded_generic': 'Лимит сессии Codex исчерпан. Попробуй позже; актуальное состояние — /usage.',
        'usage_limits_failed': 'Не удалось получить: {error}',
        'usage_limits_header': '📈 Account limits (subscription, not credits)',
        'usage_messages_line': 'Messages: {messages}',
        'usage_no_active_session': 'нет активной',
        'usage_no_data': 'нет данных',
        'usage_plan_line': 'Plan: {plan}',
        'usage_session_header': '📊 Session',
        'usage_session_line': '{thread_id}  •  Model: {model}  •  Effort: {effort}',
        'usage_tokens_header': '🔢 Tokens (this session)',
        'usage_tokens_line': 'in {input_tokens}  ·  out {output_tokens}  ·  cache-r {cache_read}  ·  cache-w {cache_write}',
        'usage_window_5h': '5-часовой лимит',
        'usage_window_reset': '{label}, сброс {reset}',
        'usage_window_weekly': 'недельный лимит',
        'workspace_missing': 'Директория не существует: {path}',
        'workspace_usage': 'Workspace: {workspace}\nИспользование: /workspace <путь>|default',
    },
    "en": {
        'access_denied': '⛔ Access to the Codex bot is not allowed. Ask the owner to add your Telegram ID to whitelist.txt.',
        'account_connected': 'connected',
        'account_not_connected': 'Codex account is not connected. Use /login.',
        'account_plan_line': '\nPlan: {plan}',
        'account_read_error': 'Could not read account: {error}',
        'account_summary': 'Account: {label}',
        'attachment_download_failed': 'File not downloaded: Telegram could not provide it. Try again or send a link.',
        'attachment_get_file_failed': 'File not downloaded: Telegram refused to provide it. Send it again or send a link.',
        'attachment_local_file_access': 'File not downloaded: cannot access the local Bot API file. Check the server and bot permissions.',
        'attachment_local_file_missing': 'File not downloaded: the local Bot API can no longer find it. Send it again or send a link.',
        'attachment_local_file_not_a_file': 'File not downloaded: the local Bot API path does not point to an accessible file. Check the server and bot permissions.',
        'attachment_network': 'File not downloaded: connection to Telegram failed. Try again or send a link.',
        'attachment_no_file_id': 'File not read: Telegram did not provide its ID.',
        'attachment_no_file_path': 'File not downloaded: Telegram did not provide a file path. Try again or send a link.',
        'attachment_no_space': 'File not downloaded: disk is full. Free up space and send the file again.',
        'attachment_loading': '📥 Loading attachment…',
        'attachment_loading_progress': '📥 Loading attachment ({done}/{total})…',
        'attachment_processing_error': 'Could not process attachment: {error}',
        'attachment_timeout': 'File not downloaded: Telegram took too long to prepare it. Try again or send a link.',
        'attachment_too_big': 'File not downloaded: it exceeds the allowed size. Send a smaller file or a link.',
        'attachment_too_big_for_cloud': 'File not downloaded: it exceeds Telegram’s 20 MB cloud limit. Enable the local Bot API server in setup.sh or send a link.',
        'attachment_too_big_for_cloud_sized': 'File not downloaded: {size_mb} MB exceeds Telegram’s 20 MB cloud limit. Enable the local Bot API server in setup.sh or send a link.',
        'attachment_voice_transcription_failed': 'Could not transcribe the voice message, so it was not read.',
        'attachment_voice_unsupported': 'Voice messages are not supported in this installation.',
        'bridge_error': '⚠️ Bridge error. Details are in the log.',
        'codex_process_died': 'the persistent Codex process ended unexpectedly',
        'codex_timed_out': 'Codex stopped after a timeout',
        'codex_unknown_error': 'Unknown Codex error',
        'context_auto_compacted': '🗜 Session context was compacted automatically.',
        'context_fill_critical': '⚠️ Context is {percent} full. Use /compact or /new.',
        'context_fill_warning': '⚠️ Context is {percent} full; you will soon need /compact.',
        'command_unknown': 'Unknown command. Open the Telegram command menu.',
        'language_usage': 'Usage: /language en|ru|uk|kk|de.',
        'language_command_description': 'Choose the interface and persona language',
        'language_changed': 'Language switched to {language}.',
        'language_persona_failed': 'Interface language switched to {language}, but the persona could not be translated: {error}',
        'context_window_exceeded': 'This session has run out of context. Use /compact to shorten the history and continue, or /new to start a new session.',
        'compact_done': '🗜 Session context compacted. You can continue.',
        'compact_failed': '🗜 Could not compact context: {error}',
        'compact_no_session': 'No active session to compact.',
        'compact_timeout': 'Context compaction timed out.',
        'compact_done_short': '🗜 Session context compacted.',
        'compact_wait_for_turn': 'Wait for the current turn to finish or use /stop first.',
        'cross_delegate_accepted': 'Accepted: the Codex bot started the task. The result will arrive in this Telegram chat from the Codex bot.',
        'cross_delegate_account_not_ready': 'Rejected: the Codex account for this Telegram ID is not ready. Finish /login in the Codex bot first.',
        'cross_delegate_already_running': 'Rejected: an earlier delegated task is still running.',
        'cross_delegate_bad_chat_id': 'Rejected: invalid Telegram chat_id.',
        'cross_delegate_empty_text': 'Rejected: task text is empty.',
        'cross_delegate_malformed_request': 'Rejected: malformed delegation request.',
        'cross_delegate_not_whitelisted': 'Rejected: this Telegram ID is not in the Codex bot’s whitelist.',
        'cross_delegate_start_failed': 'Rejected: the Codex bot could not start the delegated task.',
        'delegate_already_running': 'An earlier delegated task is still running.',
        'delegate_effort_unavailable': 'Effort “{effort}” is unavailable for {model}.',
        'delegate_model_unavailable': 'Model “{model}” is unavailable.',
        'delegate_env_resume_conflict': 'You cannot use --env together with --resume.',
        'delegate_resume_thread_mismatch': 'Cannot resume this delegation: resume_thread_id does not match the last delegated thread.',
        'delegate_settings_error': 'Could not check delegation settings: {error}',
        'delegate_start_error': 'Could not start delegated task: {error}',
        'effort_list_error': 'Could not get effort levels: {error}',
        'effort_picker_header': '⚡ Effort for {model}:',
        'effort_selected': '⚡ Effort for {model}: {effort}',
        'effort_unavailable': 'Effort “{effort}” is unavailable for {model}.\n\n{picker}',
        'effort_unsupported': 'unsupported',
        'file_send_bad_chat_id': 'Rejected: invalid Telegram chat_id.',
        'file_send_bad_path_or_caption': 'Rejected: invalid path or caption.',
        'file_send_caption_too_long': 'Rejected: caption exceeds Telegram’s limit.',
        'file_send_delivered': 'File “{name}” sent to Telegram.',
        'file_send_malformed_request': 'Rejected: malformed file sending request.',
        'file_send_not_whitelisted': 'Rejected: Telegram ID is not in the whitelist.',
        'file_send_outside_outbox': 'Rejected: the file must be a regular file in CODEX_TELEGRAM_OUTBOX.',
        'file_send_rejected': 'Telegram rejected the file: {detail}',
        'file_send_too_big': 'Rejected: file exceeds {limit} bytes.',
        'file_send_unconfirmed': 'Could not confirm file delivery: connection error or timeout ({detail}). The file was not resent to avoid a duplicate.',
        'file_over_limit': 'File exceeds the {limit}-byte limit.',
        'image_file_not_found': 'Image file not found.',
        'unknown_connection_error': 'unknown connection error',
        'unknown_error_lowercase': 'unknown error',
        'empty_placeholder': '(empty)',
        'help_intro': 'Codex Telegram bridge. Commands are in the bot menu.',
        'local_api_ask_hash': 'Send api_hash',
        'local_api_ask_id': 'Send api_id',
        'local_api_bad_url': 'The installer returned an invalid local server address',
        'local_api_configured_not_installed': '⚠️ The local server is configured but not installed on this host. Run scripts/install-local-bot-api.sh from the terminal.',
        'local_api_declined_restart': 'Okay. 🔁 Restarting the bot to apply the update…',
        'local_api_env_file_missing': '{path} not found',
        'local_api_failure': '⚠️ Could not enable the local server: {details}',
        'local_api_install_running': 'Installation is already running. Hang on.',
        'local_api_installer_failed': 'Installer exited with code {code}',
        'local_api_installer_no_url': 'Installer did not provide a local server address',
        'local_api_missing_dependencies': 'Build dependencies are missing. Run scripts/install-local-bot-api.sh from the terminal.',
        'local_api_no_sudo_permission': '⚠️ Cannot restart the server: a sudoers grant is needed.',
        'local_api_offer': 'Enable file uploads up to 2 GB through a local Bot API server? Reply yes or no.',
        'local_api_preparing': '⏳ Preparing the local Bot API server…',
        'local_api_ready_restarting': '✅ Done. Restarting the bot…',
        'local_api_restart_failed': '⚠️ Could not restart the local server: {error}',
        'local_api_restart_ineffective': '⚠️ Could not restart the local server: its service or port did not become active.',
        'local_api_restart_now': '🔁 Restarting the bot to apply the update…',
        'local_api_reuse_existing': '✅ Found an existing configured local server; no rebuild needed.',
        'local_api_stage_build': '⏳ Building the local Bot API server (may take ~15 minutes)…',
        'local_api_stage_dependencies': '⏳ Checking build dependencies…',
        'local_api_stage_done': '✅ Local server built.',
        'local_api_stage_install': '⏳ Installing the service…',
        'local_api_switch_failed': 'Switch script exited with code {code}',
        'local_api_was_inactive_restarted': '🔧 The local server was inactive; restarted it.',
        'login_complete': '✅ Signed in to Codex.',
        'login_complete_ask_name': '✅ Signed in to Codex.\n\nWhat should I call you?',
        'login_complete_first': 'Finish signing in to Codex using the link you received earlier.',
        'login_device_instructions': '🔐 Connecting a separate Codex account\n\n1. Open: {verification_url}\n2. Enter code: {user_code}\n\nTokens will be saved only in your isolated CODEX_HOME. The bot will let you know when sign-in is complete.',
        'login_failed': '❌ Sign-in did not complete: {error}',
        'login_owner_not_needed': 'The owner uses the main ~/.codex account; separate sign-in is not needed.',
        'login_start_error': 'Could not start Codex sign-in: {error}',
        'login_unknown_error': 'unknown error',
        'mode_usage': 'Usage: /mode read-only|workspace-write|full',
        'model_empty': 'Codex did not return any available models.',
        'model_list_error': 'Could not get model list: {error}',
        'model_picker_empty': 'Model list is empty.',
        'model_picker_header': '🧠 Available models:',
        'model_selected': '🧠 Model: {model}\nEffort: {effort}',
        'model_unavailable': 'Model “{model}” is unavailable.\n\n{picker}',
        'name_remembered': '✅ I’ll remember what to call you.',
        'new_previous_turn_finishing': 'The previous turn is still finishing; /new has not run yet.',
        'new_thread_reset': '🆕 Current Codex thread reset. Your next message will start a new one.',
        'persona_current_caption': 'Current persona',
        'process_agent_default_tool': 'agent work',
        'process_agent_label': '🤖 Agent · {tool}',
        'process_agent_message_label': '💬 Response',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'session context compacted',
        'process_context_compaction_label': '🗜 Context compaction',
        'process_dynamic_tool_default_name': 'tool',
        'process_error_label': '❌ Error',
        'process_exit_code_fail': '❌ Exit code',
        'process_exit_code_ok': '✅ Exit code',
        'process_file_change_add': 'created',
        'process_file_change_delete': 'deleted',
        'process_file_change_fallback': 'file changed',
        'process_file_change_label': '📝 File change',
        'process_file_change_update': 'updated',
        'process_image_fallback': 'image',
        'process_image_generation_in_progress': 'generating image',
        'process_image_generation_label': '🎨 Image generation',
        'process_image_view_label': '🖼 View image',
        'process_plan_fallback': 'plan updated',
        'process_plan_label': '📋 Plan',
        'process_reasoning_label': '🧠 Reasoning',
        'process_result_generic': 'result received',
        'process_result_label': '📤 Result',
        'process_review_entered': 'review mode enabled',
        'process_review_exited': 'review mode ended',
        'process_review_label': '🔍 Review',
        'process_sleep_label': '⏳ Waiting',
        'process_sleep_seconds': '{seconds} s',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Tool',
        'process_web_search_default_query': 'search',
        'process_web_search_find_in_page': 'finding on page',
        'process_web_search_label': '🔎 Search',
        'process_web_search_open_page': 'opening page',
        'process_web_search_searching': 'searching the web',
        'process_details_block': '<details><summary>🔧 Process ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…and {hidden} more steps above…',
        'thinking_placeholder': 'Thinking',
        'turn_codex_error': '⚠️ Codex error: {error}',
        'turn_delegation_footer': '\n\nResume the delegated session: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nYour session id (before delegation): `{prior_thread_id}`. Resume the delegated one: `/resume {thread_id}`',
        'turn_no_answer': '(no answer — see the process above)',
        'turn_stopped': '⏹ Execution stopped.',
        'turn_tokens_line': '\n\nTokens: {usage}',
        'persona_empty': 'Empty persona was not saved.',
        'persona_file_read_error': 'Could not read persona file: {error}',
        'persona_file_type_error': 'Persona file must be a UTF-8 Markdown text file.',
        'persona_owner_only': 'Persona is available only to the owner in a private chat.',
        'persona_reply_prompt': 'Reply with persona text or a UTF-8 Markdown file.',
        'persona_reset_done': '✅ Persona reset to the default template.',
        'persona_updated': '✅ Persona updated.',
        'persona_usage': 'Usage: /persona or /persona reset',
        'restart_after_turn': '🔄 Current turn finished. Restarting the Codex bot…',
        'restart_complete': '✅ Restart complete. The bot is ready.',
        'restart_in_progress': '🔄 Restart is already starting; your message was not accepted yet.',
        'restart_owner_only': 'Only the bot owner can restart it.',
        'resume_ambiguous': 'Give an unambiguous id/prefix: /resume <id>',
        'resume_delegated_kind': 'delegated ',
        'resume_not_found': 'Session not found.',
        'resume_previous_turn_finishing': 'The previous turn is still finishing; /resume has not run yet.',
        'resume_success': 'Resuming {kind}session {thread_id}.',
        'session_budget_exceeded': 'This session’s budget is exhausted. Start a new one with /new.',
        'session_missing_new_started': 'The previous session was not found; a new Codex session has started.',
        'sessions_current_marker': ' ← current',
        'sessions_list': 'Recent sessions:\n{rows}',
        'sessions_none': 'none found',
        'status_account_unlinked': 'not connected',
        'status_no': 'no',
        'status_no_session': 'none',
        'status_report': 'ℹ️ Status\nSession: {thread_id}\nModel: {model}\nEffort: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nBusy: {busy}\nAccount: {account_status}',
        'status_unknown': 'unknown',
        'status_yes': 'yes',
        'stop_idle': 'Nothing to stop right now.',
        'stop_running': '⏹ Stopping the current Codex run.',
        'update_failed': '❌ Update failed:\n```\n{error}\n```',
        'update_owner_only': 'Only the bot owner can update it.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Restart scheduled after the current turn finishes.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Restart scheduled between turns.',
        'update_done_default_summary': 'Update complete.',
        'update_script_failed': 'update.sh exited with code {code}',
        'update_start': '⬇️ Updating from git...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: {used}% used · {remaining}% left · resets {reset}',
        'rate_limit_no_data': '{label}: no data',
        'relative_time_days_hours': 'in {days} d {hours} h',
        'relative_time_hours_minutes': 'in {hours} h {minutes} min',
        'relative_time_minutes': 'in {value} min',
        'usage_context_line': 'Context: {context}',
        'usage_context_tokens': '~{tokens} tokens',
        'usage_cost_api_equivalent': '(~${usd} at equivalent API rates)',
        'usage_cost_error': 'Cost: could not retrieve ({error})',
        'usage_cost_unavailable': 'Cost: unavailable for the current subscription route',
        'usage_credits_line': 'Credits: {balance}',
        'usage_effort_unknown': 'unknown',
        'usage_label_cached': 'cached',
        'usage_label_in': 'in',
        'usage_label_out': 'out',
        'usage_label_reasoning': 'reasoning',
        'usage_limit_exceeded_details': '⏳ Codex session limit reached: {details}. You can continue this thread after the limit resets.',
        'usage_limit_exceeded_generic': 'Codex session limit reached. Try again later; check /usage for the current status.',
        'usage_limits_failed': 'Could not retrieve: {error}',
        'usage_limits_header': '📈 Account limits (subscription, not credits)',
        'usage_messages_line': 'Messages: {messages}',
        'usage_no_active_session': 'none active',
        'usage_no_data': 'no data',
        'usage_plan_line': 'Plan: {plan}',
        'usage_session_header': '📊 Session',
        'usage_session_line': '{thread_id}  •  Model: {model}  •  Effort: {effort}',
        'usage_tokens_header': '🔢 Tokens (this session)',
        'usage_tokens_line': 'in {input_tokens}  ·  out {output_tokens}  ·  cache-r {cache_read}  ·  cache-w {cache_write}',
        'usage_window_5h': '5-hour limit',
        'usage_window_reset': '{label}, resets {reset}',
        'usage_window_weekly': 'weekly limit',
        'workspace_missing': 'Directory does not exist: {path}',
        'workspace_usage': 'Workspace: {workspace}\nUsage: /workspace <path>|default',
    },
    "uk": {
        'access_denied': '⛔ Доступ до Codex-бота закрито. Попроси власника додати твій Telegram ID до whitelist.txt.',
        'account_connected': 'підключено',
        'account_not_connected': 'Акаунт Codex не підключено. Скористайся /login.',
        'account_plan_line': '\nПлан: {plan}',
        'account_read_error': 'Не вдалося прочитати дані акаунта: {error}',
        'account_summary': 'Акаунт: {label}',
        'attachment_download_failed': 'Файл не завантажено: Telegram не надав його. Спробуй ще раз або надішли посилання.',
        'attachment_get_file_failed': 'Файл не завантажено: Telegram відмовився його надати. Надішли файл ще раз або дай посилання.',
        'attachment_local_file_access': 'Файл не завантажено: немає доступу до файлу локального Bot API. Перевір права сервера й бота.',
        'attachment_local_file_missing': 'Файл не завантажено: локальний Bot API більше його не бачить. Надішли файл ще раз або дай посилання.',
        'attachment_local_file_not_a_file': 'Файл не завантажено: шлях локального Bot API не вказує на доступний файл. Перевір права сервера й бота.',
        'attachment_network': 'Файл не завантажено: збій з’єднання з Telegram. Спробуй ще раз або надішли посилання.',
        'attachment_no_file_id': 'Файл не прочитано: Telegram не передав його ідентифікатор.',
        'attachment_no_file_path': 'Файл не завантажено: Telegram не повернув шлях до нього. Спробуй ще раз або надішли посилання.',
        'attachment_no_space': 'Файл не завантажено: на диску бракує місця. Звільни місце й надішли файл ще раз.',
        'attachment_loading': '📥 Завантажую вкладення…',
        'attachment_loading_progress': '📥 Завантажую вкладення ({done}/{total})…',
        'attachment_processing_error': 'Не вдалося обробити вкладення: {error}',
        'attachment_timeout': 'Файл не завантажено: Telegram надто довго його готував. Спробуй ще раз або надішли посилання.',
        'attachment_too_big': 'Файл не завантажено: його розмір перевищує дозволений. Надішли менший файл або посилання.',
        'attachment_too_big_for_cloud': 'Файл не завантажено: його розмір перевищує хмарний ліміт Telegram у 20 МБ. Увімкни локальний сервер Bot API через setup.sh або надішли посилання.',
        'attachment_too_big_for_cloud_sized': 'Файл не завантажено: {size_mb} МБ перевищує хмарний ліміт Telegram у 20 МБ. Увімкни локальний сервер Bot API через setup.sh або надішли посилання.',
        'attachment_voice_transcription_failed': 'Не вдалося розпізнати голосове повідомлення, тому його не прочитано.',
        'attachment_voice_unsupported': 'Ця інсталяція не підтримує голосові повідомлення.',
        'bridge_error': '⚠️ Помилка мосту. Подробиці записано в журналі.',
        'codex_process_died': 'постійний процес Codex несподівано завершився',
        'codex_timed_out': 'Codex зупинено через перевищення часу очікування',
        'codex_unknown_error': 'Невідома помилка Codex',
        'context_auto_compacted': '🗜 Контекст сеансу автоматично стиснуто.',
        'context_fill_critical': '⚠️ Контекст заповнено на {percent}. Скористайся /compact або /new.',
        'context_fill_warning': '⚠️ Контекст заповнено на {percent}; незабаром знадобиться /compact.',
        'command_unknown': 'Невідома команда. Відкрий меню команд Telegram.',
        'language_usage': 'Використання: /language en|ru|uk|kk|de.',
        'language_command_description': 'Обрати мову інтерфейсу й персони',
        'language_changed': 'Мову змінено на {language}.',
        'language_persona_failed': 'Мову інтерфейсу змінено на {language}, але перекласти персону не вдалося: {error}',
        'context_window_exceeded': 'Контекст цього сеансу вичерпано. Скористайся /compact, щоб стиснути історію й продовжити, або /new, щоб почати новий сеанс.',
        'compact_done': '🗜 Контекст сеансу стиснуто. Можна продовжувати.',
        'compact_failed': '🗜 Не вдалося стиснути контекст: {error}',
        'compact_no_session': 'Немає активного сеансу для стискання.',
        'compact_timeout': 'Час очікування стискання контексту минув.',
        'compact_done_short': '🗜 Контекст сеансу стиснуто.',
        'compact_wait_for_turn': 'Спершу дочекайся завершення поточного ходу або скористайся /stop.',
        'cross_delegate_accepted': 'Прийнято: Codex-бот запустив завдання. Результат надійде від нього в цей Telegram-чат.',
        'cross_delegate_account_not_ready': 'Відхилено: акаунт Codex для цього Telegram ID ще не готовий. Спершу заверши /login у Codex-боті.',
        'cross_delegate_already_running': 'Відхилено: попереднє делеговане завдання ще виконується.',
        'cross_delegate_bad_chat_id': 'Відхилено: некоректний Telegram chat_id.',
        'cross_delegate_empty_text': 'Відхилено: текст завдання порожній.',
        'cross_delegate_malformed_request': 'Відхилено: пошкоджений формат запиту на делегування.',
        'cross_delegate_not_whitelisted': 'Відхилено: цього Telegram ID немає у whitelist Codex-бота.',
        'cross_delegate_start_failed': 'Відхилено: Codex-бот не зміг запустити делеговане завдання.',
        'delegate_already_running': 'Попереднє делеговане завдання ще виконується.',
        'delegate_effort_unavailable': 'Рівень зусиль «{effort}» недоступний для {model}.',
        'delegate_model_unavailable': 'Модель «{model}» недоступна.',
        'delegate_env_resume_conflict': 'Не можна використовувати --env разом із --resume.',
        'delegate_resume_thread_mismatch': 'Не вдається продовжити це делегування: resume_thread_id не збігається з останнім делегованим тредом.',
        'delegate_settings_error': 'Не вдалося перевірити налаштування делегування: {error}',
        'delegate_start_error': 'Не вдалося запустити делеговане завдання: {error}',
        'effort_list_error': 'Не вдалося отримати рівні зусиль: {error}',
        'effort_picker_header': '⚡ Рівень зусиль для {model}:',
        'effort_selected': '⚡ Рівень зусиль для {model}: {effort}',
        'effort_unavailable': 'Рівень зусиль «{effort}» недоступний для {model}.\n\n{picker}',
        'effort_unsupported': 'не підтримується',
        'file_send_bad_chat_id': 'Відхилено: некоректний Telegram chat_id.',
        'file_send_bad_path_or_caption': 'Відхилено: некоректний шлях або підпис.',
        'file_send_caption_too_long': 'Відхилено: підпис перевищує ліміт Telegram.',
        'file_send_delivered': 'Файл «{name}» надіслано в Telegram.',
        'file_send_malformed_request': 'Відхилено: пошкоджений запит на надсилання файлу.',
        'file_send_not_whitelisted': 'Відхилено: Telegram ID немає у whitelist.',
        'file_send_outside_outbox': 'Відхилено: файл має бути звичайним файлом у CODEX_TELEGRAM_OUTBOX.',
        'file_send_rejected': 'Telegram не прийняв файл: {detail}',
        'file_send_too_big': 'Відхилено: файл перевищує {limit} байтів.',
        'file_send_unconfirmed': 'Не вдалося підтвердити надсилання файлу: збій з’єднання або перевищення часу очікування ({detail}). Файл не надсилали повторно, щоб уникнути дубля.',
        'file_over_limit': 'Файл перевищує ліміт у {limit} байтів.',
        'image_file_not_found': 'Файл зображення не знайдено.',
        'unknown_connection_error': 'невідома помилка з’єднання',
        'unknown_error_lowercase': 'невідома помилка',
        'empty_placeholder': '(порожньо)',
        'help_intro': 'Codex Telegram bridge. Команди є в меню бота.',
        'local_api_ask_hash': 'Надішли api_hash',
        'local_api_ask_id': 'Надішли api_id',
        'local_api_bad_url': 'Інсталятор повернув некоректну адресу локального сервера',
        'local_api_configured_not_installed': '⚠️ Локальний сервер налаштовано, але не встановлено на цьому хості — запусти scripts/install-local-bot-api.sh у терміналі вручну.',
        'local_api_declined_restart': 'Гаразд. 🔁 Перезапускаю бота, щоб зміни набули чинності…',
        'local_api_env_file_missing': 'Не знайдено {path}',
        'local_api_failure': '⚠️ Не вдалося ввімкнути локальний сервер: {details}',
        'local_api_install_running': 'Установлення вже триває, зачекай.',
        'local_api_installer_failed': 'Інсталятор завершився з кодом {code}',
        'local_api_installer_no_url': 'Інсталятор не повідомив адресу локального сервера',
        'local_api_missing_dependencies': 'Бракує залежностей для збирання. Запусти scripts/install-local-bot-api.sh у терміналі вручну.',
        'local_api_no_sudo_permission': '⚠️ Немає прав на перезапуск сервера: потрібен дозвіл sudoers.',
        'local_api_offer': 'Увімкнути приймання файлів до 2 ГБ через локальний сервер Bot API? Відповідай yes або no.',
        'local_api_preparing': '⏳ Готую локальний сервер Bot API…',
        'local_api_ready_restarting': '✅ Готово. Перезапускаю бота…',
        'local_api_restart_failed': '⚠️ Не вдалося перезапустити локальний сервер: {error}',
        'local_api_restart_ineffective': '⚠️ Не вдалося перезапустити локальний сервер: служба або її порт не стали активними.',
        'local_api_restart_now': '🔁 Перезапускаю бота, щоб зміни набули чинності…',
        'local_api_reuse_existing': '✅ Знайдено вже налаштований локальний сервер; збирати його знову не потрібно.',
        'local_api_stage_build': '⏳ Збираю локальний сервер Bot API (це може зайняти ~15 хвилин)…',
        'local_api_stage_dependencies': '⏳ Перевіряю залежності для збирання…',
        'local_api_stage_done': '✅ Локальний сервер зібрано.',
        'local_api_stage_install': '⏳ Установлюю службу…',
        'local_api_switch_failed': 'Скрипт перемикання завершився з кодом {code}',
        'local_api_was_inactive_restarted': '🔧 Локальний сервер був неактивний; перезапустив його.',
        'login_complete': '✅ Вхід до акаунта Codex завершено.',
        'login_complete_ask_name': '✅ Вхід до акаунта Codex завершено.\n\nЯк до тебе звертатися?',
        'login_complete_first': 'Спершу заверши вхід до Codex за посиланням, яке отримав раніше.',
        'login_device_instructions': '🔐 Підключення окремого акаунта Codex\n\n1. Відкрий: {verification_url}\n2. Введи код: {user_code}\n\nТокени збережуться лише у твоєму ізольованому CODEX_HOME. Бот повідомить, коли вхід завершиться.',
        'login_failed': '❌ Вхід не завершено: {error}',
        'login_owner_not_needed': 'Власник користується основним акаунтом ~/.codex; окремий вхід не потрібен.',
        'login_start_error': 'Не вдалося почати вхід до Codex: {error}',
        'login_unknown_error': 'невідома помилка',
        'mode_usage': 'Використання: /mode read-only|workspace-write|full',
        'model_empty': 'Codex не повернув доступних моделей.',
        'model_list_error': 'Не вдалося отримати список моделей: {error}',
        'model_picker_empty': 'Список моделей порожній.',
        'model_picker_header': '🧠 Доступні моделі:',
        'model_selected': '🧠 Модель: {model}\nРівень зусиль: {effort}',
        'model_unavailable': 'Модель «{model}» недоступна.\n\n{picker}',
        'name_remembered': '✅ Запам’ятав, як до тебе звертатися.',
        'new_previous_turn_finishing': 'Попередній хід ще завершується; /new поки не виконано.',
        'new_thread_reset': '🆕 Поточний тред Codex скинуто. Наступне повідомлення почне новий.',
        'persona_current_caption': 'Поточна персона',
        'process_agent_default_tool': 'робота агента',
        'process_agent_label': '🤖 Агент · {tool}',
        'process_agent_message_label': '💬 Відповідь',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'контекст сеансу стиснуто',
        'process_context_compaction_label': '🗜 Стискання контексту',
        'process_dynamic_tool_default_name': 'інструмент',
        'process_error_label': '❌ Помилка',
        'process_exit_code_fail': '❌ Код завершення',
        'process_exit_code_ok': '✅ Код завершення',
        'process_file_change_add': 'створено',
        'process_file_change_delete': 'видалено',
        'process_file_change_fallback': 'файл змінено',
        'process_file_change_label': '📝 Зміна файлу',
        'process_file_change_update': 'змінено',
        'process_image_fallback': 'зображення',
        'process_image_generation_in_progress': 'створюється зображення',
        'process_image_generation_label': '🎨 Створення зображення',
        'process_image_view_label': '🖼 Перегляд зображення',
        'process_plan_fallback': 'план оновлено',
        'process_plan_label': '📋 План',
        'process_reasoning_label': '🧠 Міркування',
        'process_result_generic': 'результат отримано',
        'process_result_label': '📤 Результат',
        'process_review_entered': 'режим перевірки ввімкнено',
        'process_review_exited': 'режим перевірки завершено',
        'process_review_label': '🔍 Перевірка',
        'process_sleep_label': '⏳ Очікування',
        'process_sleep_seconds': '{seconds} с',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Інструмент',
        'process_web_search_default_query': 'пошук',
        'process_web_search_find_in_page': 'шукаю на сторінці',
        'process_web_search_label': '🔎 Пошук',
        'process_web_search_open_page': 'відкриваю сторінку',
        'process_web_search_searching': 'шукаю в інтернеті',
        'process_details_block': '<details><summary>🔧 Процес ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…і ще {hidden} кроків вище…',
        'thinking_placeholder': 'Думаю',
        'turn_codex_error': '⚠️ Помилка Codex: {error}',
        'turn_delegation_footer': '\n\nПродовжити делегований сеанс: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nТвій session id (до делегування): `{prior_thread_id}`. Продовжити делегований сеанс: `/resume {thread_id}`',
        'turn_no_answer': '(немає відповіді — дивись процес вище)',
        'turn_stopped': '⏹ Виконання зупинено.',
        'turn_tokens_line': '\n\nТокени: {usage}',
        'persona_empty': 'Порожню персону не збережено.',
        'persona_file_read_error': 'Не вдалося прочитати файл персони: {error}',
        'persona_file_type_error': 'Файл персони має бути текстовим файлом UTF-8 Markdown.',
        'persona_owner_only': 'Персона доступна лише власнику в особистому чаті.',
        'persona_reply_prompt': 'Надішли текст персони або файл UTF-8 Markdown у відповідь на повідомлення.',
        'persona_reset_done': '✅ Персону скинуто до стандартного шаблону.',
        'persona_updated': '✅ Персону оновлено.',
        'persona_usage': 'Використання: /persona або /persona reset',
        'restart_after_turn': '🔄 Поточний хід завершено. Перезапускаю Codex-бота…',
        'restart_complete': '✅ Перезапуск завершено, бот готовий до роботи.',
        'restart_in_progress': '🔄 Перезапуск уже починається; повідомлення поки не прийнято.',
        'restart_owner_only': 'Перезапустити бота може лише власник.',
        'resume_ambiguous': 'Укажи однозначний id/префікс: /resume <id>',
        'resume_delegated_kind': 'делегований ',
        'resume_not_found': 'Сеанс не знайдено.',
        'resume_previous_turn_finishing': 'Попередній хід ще завершується; /resume поки не виконано.',
        'resume_success': 'Продовжую {kind}сеанс {thread_id}.',
        'session_budget_exceeded': 'Бюджет цього сеансу вичерпано. Почни новий через /new.',
        'session_missing_new_started': 'Попередній сеанс не знайдено; розпочато новий сеанс Codex.',
        'sessions_current_marker': ' ← поточний',
        'sessions_list': 'Останні сеанси:\n{rows}',
        'sessions_none': 'не знайдено',
        'status_account_unlinked': 'не підключено',
        'status_no': 'ні',
        'status_no_session': 'немає',
        'status_report': 'ℹ️ Стан\nСеанс: {thread_id}\nМодель: {model}\nРівень зусиль: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nЗайнятий: {busy}\nАкаунт: {account_status}',
        'status_unknown': 'невідомо',
        'status_yes': 'так',
        'stop_idle': 'Зараз немає чого зупиняти.',
        'stop_running': '⏹ Зупиняю поточне виконання Codex.',
        'update_failed': '❌ Оновлення не вдалося:\n```\n{error}\n```',
        'update_owner_only': 'Оновити бота може лише власник.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Перезапуск заплановано після завершення поточного ходу.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Перезапуск заплановано між ходами.',
        'update_done_default_summary': 'Оновлення завершено.',
        'update_script_failed': 'update.sh завершився з кодом {code}',
        'update_start': '⬇️ Оновлюю з git...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: використано {used}% · залишилося {remaining}% · скидання {reset}',
        'rate_limit_no_data': '{label}: даних немає',
        'relative_time_days_hours': 'через {days} д {hours} год',
        'relative_time_hours_minutes': 'через {hours} год {minutes} хв',
        'relative_time_minutes': 'через {value} хв',
        'usage_context_line': 'Контекст: {context}',
        'usage_context_tokens': '~{tokens} токенів',
        'usage_cost_api_equivalent': '(~${usd} за еквівалентним тарифом API)',
        'usage_cost_error': 'Вартість: не вдалося отримати ({error})',
        'usage_cost_unavailable': 'Вартість: недоступна для поточного маршруту підписки',
        'usage_credits_line': 'Кредити: {balance}',
        'usage_effort_unknown': 'невідомий',
        'usage_label_cached': 'кешовано',
        'usage_label_in': 'вхідні',
        'usage_label_out': 'вихідні',
        'usage_label_reasoning': 'міркування',
        'usage_limit_exceeded_details': '⏳ Ліміт сеансу Codex вичерпано: {details}. Після скидання ліміту можна продовжити цей тред.',
        'usage_limit_exceeded_generic': 'Ліміт сеансу Codex вичерпано. Спробуй пізніше; поточний стан — у /usage.',
        'usage_limits_failed': 'Не вдалося отримати: {error}',
        'usage_limits_header': '📈 Ліміти акаунта (підписка, не кредити)',
        'usage_messages_line': 'Повідомлення: {messages}',
        'usage_no_active_session': 'немає активного',
        'usage_no_data': 'даних немає',
        'usage_plan_line': 'План: {plan}',
        'usage_session_header': '📊 Сеанс',
        'usage_session_line': '{thread_id}  •  Модель: {model}  •  Зусилля: {effort}',
        'usage_tokens_header': '🔢 Токени (цей сеанс)',
        'usage_tokens_line': 'вх. {input_tokens}  ·  вих. {output_tokens}  ·  кеш-чит. {cache_read}  ·  кеш-зап. {cache_write}',
        'usage_window_5h': '5-годинний ліміт',
        'usage_window_reset': '{label}, скидання {reset}',
        'usage_window_weekly': 'тижневий ліміт',
        'workspace_missing': 'Каталогу не існує: {path}',
        'workspace_usage': 'Workspace: {workspace}\nВикористання: /workspace <шлях>|default',
    },
    "kk": {
        'access_denied': '⛔ Codex ботына кіруге рұқсат жоқ. Иесінен Telegram ID-іңді whitelist.txt файлына қосуды сұра.',
        'account_connected': 'қосылған',
        'account_not_connected': 'Codex аккаунты қосылмаған. /login пәрменін қолдан.',
        'account_plan_line': '\nЖоспар: {plan}',
        'account_read_error': 'Аккаунт деректерін оқу мүмкін болмады: {error}',
        'account_summary': 'Аккаунт: {label}',
        'attachment_download_failed': 'Файл жүктелмеді: Telegram оны бере алмады. Қайта көр немесе сілтеме жібер.',
        'attachment_get_file_failed': 'Файл жүктелмеді: Telegram оны беруден бас тартты. Файлды қайта жібер немесе сілтеме бер.',
        'attachment_local_file_access': 'Файл жүктелмеді: жергілікті Bot API файлына қол жеткізу мүмкін емес. Сервер мен боттың рұқсаттарын тексер.',
        'attachment_local_file_missing': 'Файл жүктелмеді: жергілікті Bot API оны енді көрмейді. Файлды қайта жібер немесе сілтеме бер.',
        'attachment_local_file_not_a_file': 'Файл жүктелмеді: жергілікті Bot API жолы қолжетімді файлға нұсқамайды. Сервер мен боттың рұқсаттарын тексер.',
        'attachment_network': 'Файл жүктелмеді: Telegram-мен байланыс үзілді. Қайта көр немесе сілтеме жібер.',
        'attachment_no_file_id': 'Файл оқылмады: Telegram оның идентификаторын бермеді.',
        'attachment_no_file_path': 'Файл жүктелмеді: Telegram файл жолын бермеді. Қайта көр немесе сілтеме жібер.',
        'attachment_no_space': 'Файл жүктелмеді: дискіде орын жоқ. Орын босатып, файлды қайта жібер.',
        'attachment_loading': '📥 Тіркемені жүктеп жатырмын…',
        'attachment_loading_progress': '📥 Тіркемені жүктеп жатырмын ({done}/{total})…',
        'attachment_processing_error': 'Тіркемені өңдеу мүмкін болмады: {error}',
        'attachment_timeout': 'Файл жүктелмеді: Telegram оны тым ұзақ дайындады. Қайта көр немесе сілтеме жібер.',
        'attachment_too_big': 'Файл жүктелмеді: көлемі рұқсат етілген шектен асады. Кішірек файл немесе сілтеме жібер.',
        'attachment_too_big_for_cloud': 'Файл жүктелмеді: көлемі Telegram бұлтының 20 МБ шегінен асады. setup.sh арқылы жергілікті Bot API серверін қос немесе сілтеме жібер.',
        'attachment_too_big_for_cloud_sized': 'Файл жүктелмеді: {size_mb} МБ Telegram бұлтының 20 МБ шегінен асады. setup.sh арқылы жергілікті Bot API серверін қос немесе сілтеме жібер.',
        'attachment_voice_transcription_failed': 'Дауыстық хабарды мәтінге айналдыру мүмкін болмады, сондықтан ол оқылмады.',
        'attachment_voice_unsupported': 'Бұл орнатылымда дауыстық хабарларға қолдау жоқ.',
        'bridge_error': '⚠️ Көпір қатесі. Толығырақ журналға жазылды.',
        'codex_process_died': 'Codex-тің тұрақты процесі күтпеген жерден тоқтады',
        'codex_timed_out': 'Уақыт шегі асып кеткендіктен Codex тоқтатылды',
        'codex_unknown_error': 'Codex-тің белгісіз қатесі',
        'context_auto_compacted': '🗜 Сеанс контексі автоматты түрде ықшамдалды.',
        'context_fill_critical': '⚠️ Контекст {percent} толды. /compact немесе /new қолдан.',
        'context_fill_warning': '⚠️ Контекст {percent} толды; жақында /compact қажет болады.',
        'command_unknown': 'Белгісіз пәрмен. Telegram пәрмендер мәзірін аш.',
        'language_usage': 'Қолданылуы: /language en|ru|uk|kk|de.',
        'language_command_description': 'Интерфейс пен персона тілін таңдау',
        'language_changed': 'Тіл {language} тіліне ауыстырылды.',
        'language_persona_failed': 'Интерфейс тілі {language} тіліне ауыстырылды, бірақ персонаны аудару мүмкін болмады: {error}',
        'context_window_exceeded': 'Бұл сеанстың контексті таусылды. Тарихты ықшамдап жалғастыру үшін /compact, жаңа сеанс бастау үшін /new қолдан.',
        'compact_done': '🗜 Сеанс контексі ықшамдалды. Жалғастыра бер.',
        'compact_failed': '🗜 Контексті ықшамдау мүмкін болмады: {error}',
        'compact_no_session': 'Ықшамдайтын белсенді сеанс жоқ.',
        'compact_timeout': 'Контексті ықшамдау уақыты аяқталды.',
        'compact_done_short': '🗜 Сеанс контексі ықшамдалды.',
        'compact_wait_for_turn': 'Алдымен ағымдағы қадамның аяқталуын күт немесе /stop қолдан.',
        'cross_delegate_accepted': 'Қабылданды: Codex боты тапсырманы бастады. Нәтиже осы Telegram чатына Codex ботынан келеді.',
        'cross_delegate_account_not_ready': 'Қабылданбады: бұл Telegram ID үшін Codex аккаунты әлі дайын емес. Алдымен Codex ботында /login әрекетін аяқта.',
        'cross_delegate_already_running': 'Қабылданбады: алдыңғы тапсырылған жұмыс әлі орындалып жатыр.',
        'cross_delegate_bad_chat_id': 'Қабылданбады: Telegram chat_id жарамсыз.',
        'cross_delegate_empty_text': 'Қабылданбады: тапсырма мәтіні бос.',
        'cross_delegate_malformed_request': 'Қабылданбады: тапсырма беру сұрауының пішімі бұзылған.',
        'cross_delegate_not_whitelisted': 'Қабылданбады: бұл Telegram ID Codex ботының whitelist тізімінде жоқ.',
        'cross_delegate_start_failed': 'Қабылданбады: Codex боты тапсырылған жұмысты бастай алмады.',
        'delegate_already_running': 'Алдыңғы тапсырылған жұмыс әлі орындалып жатыр.',
        'delegate_effort_unavailable': '«{effort}» күш салу деңгейі {model} үшін қолжетімсіз.',
        'delegate_model_unavailable': '«{model}» моделі қолжетімсіз.',
        'delegate_env_resume_conflict': '--env пен --resume параметрлерін бірге қолдануға болмайды.',
        'delegate_resume_thread_mismatch': 'Бұл тапсырылған жұмысты жалғастыру мүмкін емес: resume_thread_id соңғы тапсырылған тредке сәйкес келмейді.',
        'delegate_settings_error': 'Тапсырма беру баптауларын тексеру мүмкін болмады: {error}',
        'delegate_start_error': 'Тапсырылған жұмысты бастау мүмкін болмады: {error}',
        'effort_list_error': 'Күш салу деңгейлерін алу мүмкін болмады: {error}',
        'effort_picker_header': '⚡ {model} моделінің күш салу деңгейі:',
        'effort_selected': '⚡ {model} моделінің күш салу деңгейі: {effort}',
        'effort_unavailable': '«{effort}» күш салу деңгейі {model} үшін қолжетімсіз.\n\n{picker}',
        'effort_unsupported': 'қолдау көрсетілмейді',
        'file_send_bad_chat_id': 'Қабылданбады: Telegram chat_id жарамсыз.',
        'file_send_bad_path_or_caption': 'Қабылданбады: жол немесе қолтаңба жарамсыз.',
        'file_send_caption_too_long': 'Қабылданбады: қолтаңба Telegram шегінен ұзын.',
        'file_send_delivered': '«{name}» файлы Telegram-ға жіберілді.',
        'file_send_malformed_request': 'Қабылданбады: файл жіберу сұрауының пішімі бұзылған.',
        'file_send_not_whitelisted': 'Қабылданбады: Telegram ID whitelist тізімінде жоқ.',
        'file_send_outside_outbox': 'Қабылданбады: файл CODEX_TELEGRAM_OUTBOX ішіндегі кәдімгі файл болуы керек.',
        'file_send_rejected': 'Telegram файлды қабылдамады: {detail}',
        'file_send_too_big': 'Қабылданбады: файл көлемі {limit} байттан асады.',
        'file_send_unconfirmed': 'Файлдың жеткізілгенін растау мүмкін болмады: байланыс қатесі немесе уақыт шегінің асуы ({detail}). Қайталанып кетпеуі үшін файл қайта жіберілмеді.',
        'file_over_limit': 'Файл көлемі {limit} байт шегінен асады.',
        'image_file_not_found': 'Сурет файлы табылмады.',
        'unknown_connection_error': 'белгісіз байланыс қатесі',
        'unknown_error_lowercase': 'белгісіз қате',
        'empty_placeholder': '(бос)',
        'help_intro': 'Codex Telegram bridge. Пәрмендер бот мәзірінде бар.',
        'local_api_ask_hash': 'api_hash жібер',
        'local_api_ask_id': 'api_id жібер',
        'local_api_bad_url': 'Орнатқыш жергілікті сервердің жарамсыз мекенжайын қайтарды',
        'local_api_configured_not_installed': '⚠️ Жергілікті сервер бапталған, бірақ бұл хостқа орнатылмаған — терминалда scripts/install-local-bot-api.sh файлын қолмен іске қос.',
        'local_api_declined_restart': 'Жарайды. 🔁 Өзгеріс күшіне енуі үшін ботты қайта іске қосамын…',
        'local_api_env_file_missing': '{path} табылмады',
        'local_api_failure': '⚠️ Жергілікті серверді қосу мүмкін болмады: {details}',
        'local_api_install_running': 'Орнату жүріп жатыр, күте тұр.',
        'local_api_installer_failed': 'Орнатқыш {code} кодымен аяқталды',
        'local_api_installer_no_url': 'Орнатқыш жергілікті сервердің мекенжайын бермеді',
        'local_api_missing_dependencies': 'Құрастыруға қажет тәуелділіктер жетіспейді. Терминалда scripts/install-local-bot-api.sh файлын қолмен іске қос.',
        'local_api_no_sudo_permission': '⚠️ Серверді қайта іске қосуға рұқсат жоқ: sudoers рұқсаты керек.',
        'local_api_offer': 'Жергілікті Bot API сервері арқылы 2 ГБ-қа дейінгі файлдарды қабылдауды қосайын ба? yes немесе no деп жауап бер.',
        'local_api_preparing': '⏳ Жергілікті Bot API серверін дайындап жатырмын…',
        'local_api_ready_restarting': '✅ Дайын. Ботты қайта іске қосамын…',
        'local_api_restart_failed': '⚠️ Жергілікті серверді қайта іске қосу мүмкін болмады: {error}',
        'local_api_restart_ineffective': '⚠️ Жергілікті серверді қайта іске қосу мүмкін болмады: қызметі не порты белсенді күйге өтпеді.',
        'local_api_restart_now': '🔁 Өзгеріс күшіне енуі үшін ботты қайта іске қосамын…',
        'local_api_reuse_existing': '✅ Бапталған жергілікті сервер табылды; қайта құрастыру қажет емес.',
        'local_api_stage_build': '⏳ Жергілікті Bot API серверін құрастырып жатырмын (~15 минут алуы мүмкін)…',
        'local_api_stage_dependencies': '⏳ Құрастыруға қажет тәуелділіктерді тексеріп жатырмын…',
        'local_api_stage_done': '✅ Жергілікті сервер құрастырылды.',
        'local_api_stage_install': '⏳ Қызметті орнатып жатырмын…',
        'local_api_switch_failed': 'Ауыстыру скрипті {code} кодымен аяқталды',
        'local_api_was_inactive_restarted': '🔧 Жергілікті сервер белсенді емес еді; қайта іске қостым.',
        'login_complete': '✅ Codex аккаунтына кіру аяқталды.',
        'login_complete_ask_name': '✅ Codex аккаунтына кіру аяқталды.\n\nСаған қалай жүгінейін?',
        'login_complete_first': 'Алдымен бұрын берілген сілтеме арқылы Codex жүйесіне кіруді аяқта.',
        'login_device_instructions': '🔐 Жеке Codex аккаунтын қосу\n\n1. Аш: {verification_url}\n2. Кодты енгіз: {user_code}\n\nТокендер тек өзіңе оқшауланған CODEX_HOME ішінде сақталады. Кіру аяқталғанда бот хабарлайды.',
        'login_failed': '❌ Кіру аяқталмады: {error}',
        'login_owner_not_needed': 'Бот иесі негізгі ~/.codex аккаунтын қолданады; бөлек кіру қажет емес.',
        'login_start_error': 'Codex жүйесіне кіруді бастау мүмкін болмады: {error}',
        'login_unknown_error': 'белгісіз қате',
        'mode_usage': 'Қолданылуы: /mode read-only|workspace-write|full',
        'model_empty': 'Codex қолжетімді модельдер тізімін бермеді.',
        'model_list_error': 'Модельдер тізімін алу мүмкін болмады: {error}',
        'model_picker_empty': 'Модельдер тізімі бос.',
        'model_picker_header': '🧠 Қолжетімді модельдер:',
        'model_selected': '🧠 Модель: {model}\nКүш салу деңгейі: {effort}',
        'model_unavailable': '«{model}» моделі қолжетімсіз.\n\n{picker}',
        'name_remembered': '✅ Саған қалай жүгіну керегін есте сақтадым.',
        'new_previous_turn_finishing': 'Алдыңғы қадам әлі аяқталып жатыр; /new әзірге орындалмады.',
        'new_thread_reset': '🆕 Ағымдағы Codex треді тазартылды. Келесі хабарлама жаңасын бастайды.',
        'persona_current_caption': 'Ағымдағы персона',
        'process_agent_default_tool': 'агент жұмысы',
        'process_agent_label': '🤖 Агент · {tool}',
        'process_agent_message_label': '💬 Жауап',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'сеанс контексі ықшамдалды',
        'process_context_compaction_label': '🗜 Контексті ықшамдау',
        'process_dynamic_tool_default_name': 'құрал',
        'process_error_label': '❌ Қате',
        'process_exit_code_fail': '❌ Аяқталу коды',
        'process_exit_code_ok': '✅ Аяқталу коды',
        'process_file_change_add': 'жасалды',
        'process_file_change_delete': 'жойылды',
        'process_file_change_fallback': 'файл өзгерді',
        'process_file_change_label': '📝 Файл өзгерісі',
        'process_file_change_update': 'жаңартылды',
        'process_image_fallback': 'сурет',
        'process_image_generation_in_progress': 'сурет жасалып жатыр',
        'process_image_generation_label': '🎨 Сурет жасау',
        'process_image_view_label': '🖼 Суретті қарау',
        'process_plan_fallback': 'жоспар жаңартылды',
        'process_plan_label': '📋 Жоспар',
        'process_reasoning_label': '🧠 Пайымдау',
        'process_result_generic': 'нәтиже алынды',
        'process_result_label': '📤 Нәтиже',
        'process_review_entered': 'тексеру режимі қосылды',
        'process_review_exited': 'тексеру режимі аяқталды',
        'process_review_label': '🔍 Тексеру',
        'process_sleep_label': '⏳ Күту',
        'process_sleep_seconds': '{seconds} с',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Құрал',
        'process_web_search_default_query': 'іздеу',
        'process_web_search_find_in_page': 'беттен іздеп жатырмын',
        'process_web_search_label': '🔎 Іздеу',
        'process_web_search_open_page': 'бетті ашып жатырмын',
        'process_web_search_searching': 'интернеттен іздеп жатырмын',
        'process_details_block': '<details><summary>🔧 Процесс ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…жоғарыда тағы {hidden} қадам бар…',
        'thinking_placeholder': 'Ойланып жатырмын',
        'turn_codex_error': '⚠️ Codex қатесі: {error}',
        'turn_delegation_footer': '\n\nТапсырылған сеансты жалғастыру: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nСенің session id (тапсырма берілгенге дейін): `{prior_thread_id}`. Тапсырылған сеансты жалғастыру: `/resume {thread_id}`',
        'turn_no_answer': '(жауап жоқ — жоғарыдағы процесті қара)',
        'turn_stopped': '⏹ Орындау тоқтатылды.',
        'turn_tokens_line': '\n\nТокендер: {usage}',
        'persona_empty': 'Бос персона сақталмады.',
        'persona_file_read_error': 'Персона файлын оқу мүмкін болмады: {error}',
        'persona_file_type_error': 'Персона файлы UTF-8 Markdown мәтіндік файлы болуы керек.',
        'persona_owner_only': 'Персона тек бот иесіне жеке чатта қолжетімді.',
        'persona_reply_prompt': 'Хабарламаға жауап ретінде персона мәтінін немесе UTF-8 Markdown файлын жібер.',
        'persona_reset_done': '✅ Персона әдепкі үлгіге қайтарылды.',
        'persona_updated': '✅ Персона жаңартылды.',
        'persona_usage': 'Қолданылуы: /persona немесе /persona reset',
        'restart_after_turn': '🔄 Ағымдағы қадам аяқталды. Codex ботын қайта іске қосамын…',
        'restart_complete': '✅ Қайта іске қосылды. Бот жұмысқа дайын.',
        'restart_in_progress': '🔄 Қайта іске қосу басталып жатыр; хабарлама әзірге қабылданбады.',
        'restart_owner_only': 'Ботты тек иесі қайта іске қоса алады.',
        'resume_ambiguous': 'Бірмәнді id/префикс көрсет: /resume <id>',
        'resume_delegated_kind': 'тапсырылған ',
        'resume_not_found': 'Сеанс табылмады.',
        'resume_previous_turn_finishing': 'Алдыңғы қадам әлі аяқталып жатыр; /resume әзірге орындалмады.',
        'resume_success': '{kind}сеанс {thread_id} жалғасады.',
        'session_budget_exceeded': 'Бұл сеанстың бюджеті таусылды. /new арқылы жаңасын баста.',
        'session_missing_new_started': 'Алдыңғы сеанс табылмады; жаңа Codex сеансы басталды.',
        'sessions_current_marker': ' ← ағымдағы',
        'sessions_list': 'Соңғы сеанстар:\n{rows}',
        'sessions_none': 'табылмады',
        'status_account_unlinked': 'қосылмаған',
        'status_no': 'жоқ',
        'status_no_session': 'жоқ',
        'status_report': 'ℹ️ Күйі\nСеанс: {thread_id}\nМодель: {model}\nКүш салу деңгейі: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nЖұмыс үстінде: {busy}\nАккаунт: {account_status}',
        'status_unknown': 'белгісіз',
        'status_yes': 'иә',
        'stop_idle': 'Қазір тоқтататын жұмыс жоқ.',
        'stop_running': '⏹ Codex-тің ағымдағы жұмысын тоқтатамын.',
        'update_failed': '❌ Жаңарту сәтсіз аяқталды:\n```\n{error}\n```',
        'update_owner_only': 'Ботты тек иесі жаңарта алады.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Қайта іске қосу ағымдағы қадам аяқталған соң жоспарланды.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Қайта іске қосу қадамдар арасына жоспарланды.',
        'update_done_default_summary': 'Жаңарту аяқталды.',
        'update_script_failed': 'update.sh {code} кодымен аяқталды',
        'update_start': '⬇️ git-тен жаңартып жатырмын...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: {used}% пайдаланылды · {remaining}% қалды · қалпына келуі {reset}',
        'rate_limit_no_data': '{label}: дерек жоқ',
        'relative_time_days_hours': '{days} күн {hours} сағаттан кейін',
        'relative_time_hours_minutes': '{hours} сағат {minutes} минуттан кейін',
        'relative_time_minutes': '{value} минуттан кейін',
        'usage_context_line': 'Контекст: {context}',
        'usage_context_tokens': '~{tokens} токен',
        'usage_cost_api_equivalent': '(API бағамымен шамамен ${usd})',
        'usage_cost_error': 'Құны: алу мүмкін болмады ({error})',
        'usage_cost_unavailable': 'Құны: ағымдағы жазылым бағыты үшін қолжетімсіз',
        'usage_credits_line': 'Кредиттер: {balance}',
        'usage_effort_unknown': 'белгісіз',
        'usage_label_cached': 'кэштелген',
        'usage_label_in': 'кіріс',
        'usage_label_out': 'шығыс',
        'usage_label_reasoning': 'пайымдау',
        'usage_limit_exceeded_details': '⏳ Codex сеансының лимиті таусылды: {details}. Лимит жаңарған соң осы тредті жалғастыра аласың.',
        'usage_limit_exceeded_generic': 'Codex сеансының лимиті таусылды. Кейінірек қайталап көр; ағымдағы күйді /usage арқылы тексер.',
        'usage_limits_failed': 'Алу мүмкін болмады: {error}',
        'usage_limits_header': '📈 Аккаунт лимиттері (жазылым, кредит емес)',
        'usage_messages_line': 'Хабарламалар: {messages}',
        'usage_no_active_session': 'белсендісі жоқ',
        'usage_no_data': 'дерек жоқ',
        'usage_plan_line': 'Жоспар: {plan}',
        'usage_session_header': '📊 Сеанс',
        'usage_session_line': '{thread_id}  •  Модель: {model}  •  Күш салу: {effort}',
        'usage_tokens_header': '🔢 Токендер (осы сеанс)',
        'usage_tokens_line': 'кіріс {input_tokens}  ·  шығыс {output_tokens}  ·  кэш-оқу {cache_read}  ·  кэш-жазу {cache_write}',
        'usage_window_5h': '5 сағаттық лимит',
        'usage_window_reset': '{label}, қалпына келуі {reset}',
        'usage_window_weekly': 'апталық лимит',
        'workspace_missing': 'Каталог жоқ: {path}',
        'workspace_usage': 'Workspace: {workspace}\nҚолданылуы: /workspace <жол>|default',
    },
    "de": {
        'access_denied': '⛔ Kein Zugriff auf den Codex-Bot. Bitte den Betreiber, deine Telegram ID in whitelist.txt einzutragen.',
        'account_connected': 'verbunden',
        'account_not_connected': 'Das Codex-Konto ist nicht verbunden. Nutze /login.',
        'account_plan_line': '\nTarif: {plan}',
        'account_read_error': 'Konto konnte nicht gelesen werden: {error}',
        'account_summary': 'Konto: {label}',
        'attachment_download_failed': 'Datei nicht heruntergeladen: Telegram konnte sie nicht bereitstellen. Versuch es erneut oder schick einen Link.',
        'attachment_get_file_failed': 'Datei nicht heruntergeladen: Telegram hat die Bereitstellung verweigert. Schick sie erneut oder sende einen Link.',
        'attachment_local_file_access': 'Datei nicht heruntergeladen: Kein Zugriff auf die Datei der lokalen Bot API. Prüfe die Rechte von Server und Bot.',
        'attachment_local_file_missing': 'Datei nicht heruntergeladen: Die lokale Bot API findet sie nicht mehr. Schick sie erneut oder sende einen Link.',
        'attachment_local_file_not_a_file': 'Datei nicht heruntergeladen: Der Pfad der lokalen Bot API zeigt nicht auf eine zugängliche Datei. Prüfe die Rechte von Server und Bot.',
        'attachment_network': 'Datei nicht heruntergeladen: Verbindungsfehler zu Telegram. Versuch es erneut oder schick einen Link.',
        'attachment_no_file_id': 'Datei nicht gelesen: Telegram hat keine Datei-ID übermittelt.',
        'attachment_no_file_path': 'Datei nicht heruntergeladen: Telegram hat keinen Dateipfad geliefert. Versuch es erneut oder schick einen Link.',
        'attachment_no_space': 'Datei nicht heruntergeladen: Die Festplatte ist voll. Schaff Platz und schick die Datei erneut.',
        'attachment_loading': '📥 Lade Anhang…',
        'attachment_loading_progress': '📥 Lade Anhang ({done}/{total})…',
        'attachment_processing_error': 'Anhang konnte nicht verarbeitet werden: {error}',
        'attachment_timeout': 'Datei nicht heruntergeladen: Telegram hat zu lange gebraucht. Versuch es erneut oder schick einen Link.',
        'attachment_too_big': 'Datei nicht heruntergeladen: Sie überschreitet die zulässige Größe. Schick eine kleinere Datei oder einen Link.',
        'attachment_too_big_for_cloud': 'Datei nicht heruntergeladen: Sie überschreitet das Cloud-Limit von Telegram (20 MB). Aktiviere den lokalen Bot API Server über setup.sh oder schick einen Link.',
        'attachment_too_big_for_cloud_sized': 'Datei nicht heruntergeladen: {size_mb} MB überschreiten das Cloud-Limit von Telegram (20 MB). Aktiviere den lokalen Bot API Server über setup.sh oder schick einen Link.',
        'attachment_voice_transcription_failed': 'Die Sprachnachricht konnte nicht transkribiert und daher nicht gelesen werden.',
        'attachment_voice_unsupported': 'Sprachnachrichten werden in dieser Installation nicht unterstützt.',
        'bridge_error': '⚠️ Fehler der Bridge. Einzelheiten stehen im Log.',
        'codex_process_died': 'der dauerhafte Codex-Prozess wurde unerwartet beendet',
        'codex_timed_out': 'Codex wurde wegen Zeitüberschreitung gestoppt',
        'codex_unknown_error': 'Unbekannter Codex-Fehler',
        'context_auto_compacted': '🗜 Der Sitzungskontext wurde automatisch komprimiert.',
        'context_fill_critical': '⚠️ Der Kontext ist zu {percent} gefüllt. Nutze /compact oder /new.',
        'context_fill_warning': '⚠️ Der Kontext ist zu {percent} gefüllt; bald brauchst du /compact.',
        'command_unknown': 'Unbekannter Befehl. Öffne das Telegram-Befehlsmenü.',
        'language_usage': 'Verwendung: /language en|ru|uk|kk|de.',
        'language_command_description': 'Sprache für Oberfläche und Persona wählen',
        'language_changed': 'Sprache auf {language} umgestellt.',
        'language_persona_failed': 'Oberfläche auf {language} umgestellt, aber die Persona konnte nicht übersetzt werden: {error}',
        'context_window_exceeded': 'Der Kontext dieser Sitzung ist erschöpft. Nutze /compact, um den Verlauf zu komprimieren und fortzufahren, oder /new für eine neue Sitzung.',
        'compact_done': '🗜 Sitzungskontext komprimiert. Du kannst weitermachen.',
        'compact_failed': '🗜 Kontext konnte nicht komprimiert werden: {error}',
        'compact_no_session': 'Keine aktive Sitzung zum Komprimieren.',
        'compact_timeout': 'Zeitüberschreitung beim Komprimieren des Kontexts.',
        'compact_done_short': '🗜 Sitzungskontext komprimiert.',
        'compact_wait_for_turn': 'Warte erst, bis der aktuelle Schritt fertig ist, oder nutze /stop.',
        'cross_delegate_accepted': 'Angenommen: Der Codex-Bot hat die Aufgabe gestartet. Das Ergebnis kommt vom Codex-Bot in diesen Telegram-Chat.',
        'cross_delegate_account_not_ready': 'Abgelehnt: Das Codex-Konto für diese Telegram ID ist noch nicht bereit. Schließe erst /login im Codex-Bot ab.',
        'cross_delegate_already_running': 'Abgelehnt: Eine frühere delegierte Aufgabe läuft noch.',
        'cross_delegate_bad_chat_id': 'Abgelehnt: ungültige Telegram chat_id.',
        'cross_delegate_empty_text': 'Abgelehnt: Der Aufgabentext ist leer.',
        'cross_delegate_malformed_request': 'Abgelehnt: fehlerhaft formatierte Delegierungsanfrage.',
        'cross_delegate_not_whitelisted': 'Abgelehnt: Diese Telegram ID steht nicht auf der whitelist des Codex-Bots.',
        'cross_delegate_start_failed': 'Abgelehnt: Der Codex-Bot konnte die delegierte Aufgabe nicht starten.',
        'delegate_already_running': 'Eine frühere delegierte Aufgabe läuft noch.',
        'delegate_effort_unavailable': 'Die Leistungsstufe „{effort}“ ist für {model} nicht verfügbar.',
        'delegate_model_unavailable': 'Das Modell „{model}“ ist nicht verfügbar.',
        'delegate_env_resume_conflict': '--env und --resume können nicht zusammen verwendet werden.',
        'delegate_resume_thread_mismatch': 'Diese Delegierung kann nicht fortgesetzt werden: resume_thread_id stimmt nicht mit dem letzten delegierten Thread überein.',
        'delegate_settings_error': 'Delegierungseinstellungen konnten nicht geprüft werden: {error}',
        'delegate_start_error': 'Delegierte Aufgabe konnte nicht gestartet werden: {error}',
        'effort_list_error': 'Leistungsstufen konnten nicht abgerufen werden: {error}',
        'effort_picker_header': '⚡ Leistungsstufe für {model}:',
        'effort_selected': '⚡ Leistungsstufe für {model}: {effort}',
        'effort_unavailable': 'Die Leistungsstufe „{effort}“ ist für {model} nicht verfügbar.\n\n{picker}',
        'effort_unsupported': 'nicht unterstützt',
        'file_send_bad_chat_id': 'Abgelehnt: ungültige Telegram chat_id.',
        'file_send_bad_path_or_caption': 'Abgelehnt: ungültiger Pfad oder Bildunterschrift.',
        'file_send_caption_too_long': 'Abgelehnt: Die Bildunterschrift überschreitet das Telegram-Limit.',
        'file_send_delivered': 'Datei „{name}“ an Telegram gesendet.',
        'file_send_malformed_request': 'Abgelehnt: fehlerhafte Anfrage zum Dateiversand.',
        'file_send_not_whitelisted': 'Abgelehnt: Telegram ID steht nicht auf der whitelist.',
        'file_send_outside_outbox': 'Abgelehnt: Die Datei muss eine reguläre Datei in CODEX_TELEGRAM_OUTBOX sein.',
        'file_send_rejected': 'Telegram hat die Datei abgelehnt: {detail}',
        'file_send_too_big': 'Abgelehnt: Die Datei überschreitet {limit} Byte.',
        'file_send_unconfirmed': 'Dateiversand konnte nicht bestätigt werden: Verbindungsfehler oder Zeitüberschreitung ({detail}). Die Datei wurde nicht erneut gesendet, um ein Duplikat zu vermeiden.',
        'file_over_limit': 'Die Datei überschreitet das Limit von {limit} Byte.',
        'image_file_not_found': 'Bilddatei nicht gefunden.',
        'unknown_connection_error': 'unbekannter Verbindungsfehler',
        'unknown_error_lowercase': 'unbekannter Fehler',
        'empty_placeholder': '(leer)',
        'help_intro': 'Codex Telegram bridge. Die Befehle stehen im Bot-Menü.',
        'local_api_ask_hash': 'Schick api_hash',
        'local_api_ask_id': 'Schick api_id',
        'local_api_bad_url': 'Der Installer hat eine ungültige Adresse für den lokalen Server geliefert',
        'local_api_configured_not_installed': '⚠️ Der lokale Server ist konfiguriert, aber auf diesem Host nicht installiert. Starte scripts/install-local-bot-api.sh manuell im Terminal.',
        'local_api_declined_restart': 'Okay. 🔁 Ich starte den Bot neu, damit die Änderung wirksam wird…',
        'local_api_env_file_missing': '{path} nicht gefunden',
        'local_api_failure': '⚠️ Lokaler Server konnte nicht aktiviert werden: {details}',
        'local_api_install_running': 'Die Installation läuft bereits. Warte kurz.',
        'local_api_installer_failed': 'Installer wurde mit Code {code} beendet',
        'local_api_installer_no_url': 'Der Installer hat keine Adresse für den lokalen Server geliefert',
        'local_api_missing_dependencies': 'Abhängigkeiten zum Bauen fehlen. Starte scripts/install-local-bot-api.sh manuell im Terminal.',
        'local_api_no_sudo_permission': '⚠️ Keine Berechtigung zum Neustart des Servers: Ein sudoers-Eintrag ist nötig.',
        'local_api_offer': 'Dateien bis 2 GB über einen lokalen Bot API Server empfangen? Antworte mit yes oder no.',
        'local_api_preparing': '⏳ Bereite den lokalen Bot API Server vor…',
        'local_api_ready_restarting': '✅ Fertig. Starte den Bot neu…',
        'local_api_restart_failed': '⚠️ Lokaler Server konnte nicht neu gestartet werden: {error}',
        'local_api_restart_ineffective': '⚠️ Lokaler Server konnte nicht neu gestartet werden: Dienst oder Port wurde nicht aktiv.',
        'local_api_restart_now': '🔁 Ich starte den Bot neu, damit die Änderung wirksam wird…',
        'local_api_reuse_existing': '✅ Ein bereits konfigurierter lokaler Server wurde gefunden; kein Neubau nötig.',
        'local_api_stage_build': '⏳ Baue den lokalen Bot API Server (kann ~15 Minuten dauern)…',
        'local_api_stage_dependencies': '⏳ Prüfe Abhängigkeiten zum Bauen…',
        'local_api_stage_done': '✅ Lokaler Server gebaut.',
        'local_api_stage_install': '⏳ Installiere den Dienst…',
        'local_api_switch_failed': 'Umschaltskript wurde mit Code {code} beendet',
        'local_api_was_inactive_restarted': '🔧 Der lokale Server war inaktiv; ich habe ihn neu gestartet.',
        'login_complete': '✅ Anmeldung bei Codex abgeschlossen.',
        'login_complete_ask_name': '✅ Anmeldung bei Codex abgeschlossen.\n\nWie soll ich dich nennen?',
        'login_complete_first': 'Schließe erst die Anmeldung bei Codex über den zuvor erhaltenen Link ab.',
        'login_device_instructions': '🔐 Separates Codex-Konto verbinden\n\n1. Öffne: {verification_url}\n2. Gib den Code ein: {user_code}\n\nDie Tokens werden nur in deinem isolierten CODEX_HOME gespeichert. Der Bot meldet sich, sobald die Anmeldung abgeschlossen ist.',
        'login_failed': '❌ Anmeldung nicht abgeschlossen: {error}',
        'login_owner_not_needed': 'Der Betreiber nutzt das Hauptkonto unter ~/.codex; eine separate Anmeldung ist nicht nötig.',
        'login_start_error': 'Codex-Anmeldung konnte nicht gestartet werden: {error}',
        'login_unknown_error': 'unbekannter Fehler',
        'mode_usage': 'Verwendung: /mode read-only|workspace-write|full',
        'model_empty': 'Codex hat keine verfügbaren Modelle geliefert.',
        'model_list_error': 'Modellliste konnte nicht abgerufen werden: {error}',
        'model_picker_empty': 'Die Modellliste ist leer.',
        'model_picker_header': '🧠 Verfügbare Modelle:',
        'model_selected': '🧠 Modell: {model}\nLeistungsstufe: {effort}',
        'model_unavailable': 'Das Modell „{model}“ ist nicht verfügbar.\n\n{picker}',
        'name_remembered': '✅ Ich habe mir gemerkt, wie ich dich ansprechen soll.',
        'new_previous_turn_finishing': 'Der vorige Schritt wird noch abgeschlossen; /new wurde noch nicht ausgeführt.',
        'new_thread_reset': '🆕 Aktueller Codex-Thread zurückgesetzt. Deine nächste Nachricht startet einen neuen.',
        'persona_current_caption': 'Aktuelle Persona',
        'process_agent_default_tool': 'Agentenarbeit',
        'process_agent_label': '🤖 Agent · {tool}',
        'process_agent_message_label': '💬 Antwort',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'Sitzungskontext komprimiert',
        'process_context_compaction_label': '🗜 Kontextkomprimierung',
        'process_dynamic_tool_default_name': 'Werkzeug',
        'process_error_label': '❌ Fehler',
        'process_exit_code_fail': '❌ Exit-Code',
        'process_exit_code_ok': '✅ Exit-Code',
        'process_file_change_add': 'erstellt',
        'process_file_change_delete': 'gelöscht',
        'process_file_change_fallback': 'Datei geändert',
        'process_file_change_label': '📝 Dateiänderung',
        'process_file_change_update': 'geändert',
        'process_image_fallback': 'Bild',
        'process_image_generation_in_progress': 'Bild wird erstellt',
        'process_image_generation_label': '🎨 Bilderstellung',
        'process_image_view_label': '🖼 Bild ansehen',
        'process_plan_fallback': 'Plan aktualisiert',
        'process_plan_label': '📋 Plan',
        'process_reasoning_label': '🧠 Überlegung',
        'process_result_generic': 'Ergebnis erhalten',
        'process_result_label': '📤 Ergebnis',
        'process_review_entered': 'Prüfmodus aktiviert',
        'process_review_exited': 'Prüfmodus beendet',
        'process_review_label': '🔍 Prüfung',
        'process_sleep_label': '⏳ Warten',
        'process_sleep_seconds': '{seconds} s',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Werkzeug',
        'process_web_search_default_query': 'Suche',
        'process_web_search_find_in_page': 'suche auf der Seite',
        'process_web_search_label': '🔎 Suche',
        'process_web_search_open_page': 'öffne die Seite',
        'process_web_search_searching': 'suche im Internet',
        'process_details_block': '<details><summary>🔧 Prozess ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…und {hidden} weitere Schritte oben…',
        'thinking_placeholder': 'Denke nach',
        'turn_codex_error': '⚠️ Codex-Fehler: {error}',
        'turn_delegation_footer': '\n\nDelegierte Sitzung fortsetzen: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nDeine session id (vor der Delegierung): `{prior_thread_id}`. Delegierte Sitzung fortsetzen: `/resume {thread_id}`',
        'turn_no_answer': '(keine Antwort – siehe Prozess oben)',
        'turn_stopped': '⏹ Ausführung gestoppt.',
        'turn_tokens_line': '\n\nTokens: {usage}',
        'persona_empty': 'Eine leere Persona wurde nicht gespeichert.',
        'persona_file_read_error': 'Persona-Datei konnte nicht gelesen werden: {error}',
        'persona_file_type_error': 'Die Persona-Datei muss eine UTF-8-Markdown-Textdatei sein.',
        'persona_owner_only': 'Die Persona ist nur für den Betreiber im privaten Chat verfügbar.',
        'persona_reply_prompt': 'Antworte mit dem Persona-Text oder einer UTF-8-Markdown-Datei.',
        'persona_reset_done': '✅ Persona auf die Standardvorlage zurückgesetzt.',
        'persona_updated': '✅ Persona aktualisiert.',
        'persona_usage': 'Verwendung: /persona oder /persona reset',
        'restart_after_turn': '🔄 Aktueller Schritt abgeschlossen. Starte den Codex-Bot neu…',
        'restart_complete': '✅ Neustart abgeschlossen. Der Bot ist bereit.',
        'restart_in_progress': '🔄 Der Neustart beginnt bereits; deine Nachricht wurde noch nicht angenommen.',
        'restart_owner_only': 'Nur der Betreiber kann den Bot neu starten.',
        'resume_ambiguous': 'Gib eine eindeutige ID oder ein eindeutiges Präfix an: /resume <id>',
        'resume_delegated_kind': 'delegierte ',
        'resume_not_found': 'Sitzung nicht gefunden.',
        'resume_previous_turn_finishing': 'Der vorige Schritt wird noch abgeschlossen; /resume wurde noch nicht ausgeführt.',
        'resume_success': 'Ich setze die {kind}Sitzung {thread_id} fort.',
        'session_budget_exceeded': 'Das Budget dieser Sitzung ist erschöpft. Starte mit /new eine neue.',
        'session_missing_new_started': 'Die vorige Sitzung wurde nicht gefunden; eine neue Codex-Sitzung wurde gestartet.',
        'sessions_current_marker': ' ← aktuell',
        'sessions_list': 'Letzte Sitzungen:\n{rows}',
        'sessions_none': 'keine gefunden',
        'status_account_unlinked': 'nicht verbunden',
        'status_no': 'nein',
        'status_no_session': 'keine',
        'status_report': 'ℹ️ Status\nSitzung: {thread_id}\nModell: {model}\nLeistungsstufe: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nBeschäftigt: {busy}\nKonto: {account_status}',
        'status_unknown': 'unbekannt',
        'status_yes': 'ja',
        'stop_idle': 'Gerade gibt es nichts zu stoppen.',
        'stop_running': '⏹ Stoppe die aktuelle Codex-Ausführung.',
        'update_failed': '❌ Aktualisierung fehlgeschlagen:\n```\n{error}\n```',
        'update_owner_only': 'Nur der Betreiber kann den Bot aktualisieren.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Neustart nach dem aktuellen Schritt geplant.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Neustart zwischen zwei Schritten geplant.',
        'update_done_default_summary': 'Aktualisierung abgeschlossen.',
        'update_script_failed': 'update.sh wurde mit Code {code} beendet',
        'update_start': '⬇️ Aktualisiere aus git...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: {used}% verbraucht · {remaining}% übrig · Zurücksetzung {reset}',
        'rate_limit_no_data': '{label}: keine Daten',
        'relative_time_days_hours': 'in {days} Tagen {hours} Std.',
        'relative_time_hours_minutes': 'in {hours} Std. {minutes} Min.',
        'relative_time_minutes': 'in {value} Min.',
        'usage_context_line': 'Kontext: {context}',
        'usage_context_tokens': '~{tokens} Tokens',
        'usage_cost_api_equivalent': '(~${usd} nach entsprechendem API-Tarif)',
        'usage_cost_error': 'Kosten: konnten nicht abgerufen werden ({error})',
        'usage_cost_unavailable': 'Kosten: für den aktuellen Abo-Zugang nicht verfügbar',
        'usage_credits_line': 'Guthaben: {balance}',
        'usage_effort_unknown': 'unbekannt',
        'usage_label_cached': 'gecacht',
        'usage_label_in': 'ein',
        'usage_label_out': 'aus',
        'usage_label_reasoning': 'Denken',
        'usage_limit_exceeded_details': '⏳ Codex-Sitzungslimit erreicht: {details}. Nach dem Zurücksetzen kannst du diesen Thread fortsetzen.',
        'usage_limit_exceeded_generic': 'Codex-Sitzungslimit erreicht. Versuch es später; den aktuellen Stand siehst du mit /usage.',
        'usage_limits_failed': 'Abruf fehlgeschlagen: {error}',
        'usage_limits_header': '📈 Kontolimits (Abo, kein Guthaben)',
        'usage_messages_line': 'Nachrichten: {messages}',
        'usage_no_active_session': 'keine aktive',
        'usage_no_data': 'keine Daten',
        'usage_plan_line': 'Tarif: {plan}',
        'usage_session_header': '📊 Sitzung',
        'usage_session_line': '{thread_id}  •  Modell: {model}  •  Leistungsstufe: {effort}',
        'usage_tokens_header': '🔢 Tokens (diese Sitzung)',
        'usage_tokens_line': 'ein {input_tokens}  ·  aus {output_tokens}  ·  Cache-Lesen {cache_read}  ·  Cache-Schreiben {cache_write}',
        'usage_window_5h': '5-Stunden-Limit',
        'usage_window_reset': '{label}, Zurücksetzung {reset}',
        'usage_window_weekly': 'Wochenlimit',
        'workspace_missing': 'Verzeichnis existiert nicht: {path}',
        'workspace_usage': 'Workspace: {workspace}\nVerwendung: /workspace <Pfad>|default',
    },
}


def t(key, lang=None, **kwargs) -> str:
    lang = lang or current_language.get()
    template = STRINGS.get(lang, {}).get(key)
    if template is None:
        template = STRINGS["ru"][key]
    return template.format(**kwargs)
