"""Bot-authored UI strings, keyed for future per-chat localization."""

import contextvars


current_language: contextvars.ContextVar[str] = contextvars.ContextVar(
    "current_language", default="ru",
)

STRINGS: dict[str, dict[str, str]] = {
    "ru": {
        'access_denied': '⛔ Доступ к Codex-боту не разрешён. Попроси владельца добавить твой Telegram ID в whitelist.txt.',
        'account_connected': 'подключён',
        'account_not_connected': 'Аккаунт Codex не подключён. Используй /login.',
        'account_plan_line': '\nПлан: {plan}',
        'account_read_error': 'Не удалось прочитать аккаунт: {error}',
        'account_summary': 'Аккаунт: {label}',
        'attachment_download_failed': 'Файл не скачан: Telegram не дал получить файл. Попробуй ещё раз или дай ссылку.',
        'attachment_get_file_failed': 'Файл не скачан: Telegram отказал в выдаче файла. Отправь его снова или дай ссылку.',
        'attachment_local_file_access': 'Файл не скачан: нет доступа к файлу локального Bot API. Проверь права сервера и бота.',
        'attachment_local_file_missing': 'Файл не скачан: локальный Bot API больше не видит этот файл. Отправь его снова или дай ссылку.',
        'attachment_local_file_not_a_file': 'Файл не скачан: путь локального Bot API не является доступным файлом. Проверь права сервера и бота.',
        'attachment_network': 'Файл не скачан: ошибка связи с Telegram. Попробуй ещё раз или дай ссылку.',
        'attachment_no_file_id': 'Файл не прочитан: Telegram не передал его идентификатор.',
        'attachment_no_file_path': 'Файл не скачан: Telegram не вернул путь к файлу. Попробуй ещё раз или дай ссылку.',
        'attachment_no_space': 'Файл не скачан: на диске нет места. Освободи место и отправь файл снова.',
        'attachment_loading': '📥 Загружаю вложение…',
        'attachment_loading_progress': '📥 Загружаю вложение ({done}/{total})…',
        'attachment_processing_error': 'Не смог обработать вложение: {error}',
        'attachment_timeout': 'Файл не скачан: Telegram слишком долго готовил файл. Попробуй ещё раз или дай ссылку.',
        'attachment_too_big': 'Файл не скачан: размер превышает разрешённый лимит. Отправь меньший файл или дай ссылку.',
        'attachment_too_big_for_cloud': 'Файл не скачан: размер файла превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API сервер в setup.sh или дай ссылку.',
        'attachment_too_big_for_cloud_sized': 'Файл не скачан: размер {size_mb} МБ превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API сервер в setup.sh или дай ссылку.',
        'attachment_voice_transcription_failed': 'Голосовое сообщение не удалось распознать и оно не прочитано.',
        'attachment_voice_unsupported': 'Голосовые сообщения не поддерживаются на этой установке.',
        'bridge_error': '⚠️ Ошибка моста. Подробности записаны в лог.',
        'codex_process_died': 'постоянный процесс Codex неожиданно завершился',
        'codex_timed_out': 'Codex остановлен по таймауту',
        'codex_unknown_error': 'Неизвестная ошибка Codex',
        'context_auto_compacted': '🗜 Контекст сессии автоматически сжат.',
        'context_fill_critical': '⚠️ Контекст заполнен на {percent}. Рекомендуется /compact или /new.',
        'context_fill_warning': '⚠️ Контекст заполнен на {percent}; скоро понадобится /compact.',
        'command_unknown': 'Неизвестная команда. Открой меню команд Telegram.',
        'language_usage': 'Использование: /language en|ru|uk|kk|de.',
        'language_command_description': 'Выбрать язык интерфейса и персоны',
        'language_changed': 'Язык переключён: {language}.',
        'language_persona_failed': 'Язык интерфейса переключён на {language}, но перевести персону не удалось: {error}',
        'context_window_exceeded': 'Контекст текущей сессии исчерпан. Используй /compact, чтобы сжать историю и продолжить, либо /new для новой сессии.',
        'compact_done': '🗜 Контекст сессии сжат. Можно продолжать.',
        'compact_failed': '🗜 Не удалось сжать контекст: {error}',
        'compact_no_session': 'Нет активной сессии для сжатия.',
        'compact_timeout': 'Сжатие контекста не завершилось за отведённое время.',
        'compact_done_short': '🗜 Контекст сессии сжат.',
        'compact_wait_for_turn': 'Сначала дождись завершения текущего хода или используй /stop.',
        'cross_delegate_accepted': 'Принято: Codex-бот запустил задачу. Результат придёт в этот же Telegram-чат от Codex-бота.',
        'cross_delegate_account_not_ready': 'Отклонено: Codex-аккаунт для этого Telegram ID не готов. Сначала заверши /login в Codex-боте.',
        'cross_delegate_already_running': 'Отклонено: уже выполняется предыдущая делегированная задача.',
        'cross_delegate_bad_chat_id': 'Отклонено: некорректный Telegram chat_id.',
        'cross_delegate_empty_text': 'Отклонено: пустой текст задачи.',
        'cross_delegate_malformed_request': 'Отклонено: повреждённый формат запроса делегации.',
        'cross_delegate_not_whitelisted': 'Отклонено: этот Telegram ID отсутствует в whitelist Codex-бота.',
        'cross_delegate_start_failed': 'Отклонено: Codex-бот не смог запустить делегированную задачу.',
        'delegate_already_running': 'Уже выполняю предыдущую делегированную задачу.',
        'delegate_effort_unavailable': 'Мощность «{effort}» недоступна для {model}.',
        'delegate_model_unavailable': 'Модель «{model}» недоступна.',
        'delegate_env_resume_conflict': 'Нельзя использовать --env вместе с --resume.',
        'delegate_resume_thread_mismatch': 'Нельзя продолжить эту делегацию: resume_thread_id не совпадает с последним делегированным тредом.',
        'delegate_settings_error': 'Не удалось проверить настройки делегации: {error}',
        'delegate_start_error': 'Не удалось запустить делегированную задачу: {error}',
        'effort_list_error': 'Не удалось получить уровни мощности: {error}',
        'effort_picker_header': '⚡ Мощность модели {model}:',
        'effort_selected': '⚡ Мощность {model}: {effort}',
        'effort_unavailable': 'Мощность «{effort}» недоступна для {model}.\n\n{picker}',
        'effort_unsupported': 'не поддерживается',
        'file_send_bad_chat_id': 'Отклонено: некорректный Telegram chat_id.',
        'file_send_bad_path_or_caption': 'Отклонено: некорректный путь или подпись.',
        'file_send_caption_too_long': 'Отклонено: подпись длиннее лимита Telegram.',
        'file_send_delivered': 'Файл «{name}» отправлен в Telegram.',
        'file_send_malformed_request': 'Отклонено: повреждённый запрос отправки файла.',
        'file_send_not_whitelisted': 'Отклонено: Telegram ID отсутствует в whitelist.',
        'file_send_outside_outbox': 'Отклонено: файл должен быть обычным файлом из CODEX_TELEGRAM_OUTBOX.',
        'file_send_rejected': 'Telegram не принял файл: {detail}',
        'file_send_too_big': 'Отклонено: файл больше {limit} байт.',
        'file_send_unconfirmed': 'Не удалось подтвердить отправку файла: ошибка связи или таймаут ({detail}). Файл не был отправлен повторно, чтобы избежать дубля.',
        'file_over_limit': 'Файл больше лимита {limit} байт.',
        'image_file_not_found': 'Файл изображения не найден.',
        'unknown_connection_error': 'неизвестная ошибка связи',
        'unknown_error_lowercase': 'неизвестная ошибка',
        'empty_placeholder': '(пусто)',
        'help_intro': 'Codex Telegram bridge. Команды доступны в меню бота.',
        'local_api_ask_hash': 'Пришли api_hash',
        'local_api_ask_id': 'Пришли api_id',
        'local_api_bad_url': 'Установщик вернул недопустимый адрес локального сервера',
        'local_api_configured_not_installed': '⚠️ Локальный сервер сконфигурирован, но не установлен на этом хосте — прогони scripts/install-local-bot-api.sh из терминала вручную.',
        'local_api_declined_restart': 'Ладно. 🔁 Перезапускаю бота, чтобы обновление вступило в силу…',
        'local_api_env_file_missing': 'Не найден {path}',
        'local_api_failure': '⚠️ Не удалось включить локальный сервер: {details}',
        'local_api_install_running': 'Установка уже идёт, дождись.',
        'local_api_installer_failed': 'Установщик завершился с кодом {code}',
        'local_api_installer_no_url': 'Установщик не сообщил адрес локального сервера',
        'local_api_missing_dependencies': 'Не хватает зависимостей сборки. Прогони scripts/install-local-bot-api.sh из терминала вручную.',
        'local_api_no_sudo_permission': '⚠️ Нет прав перезапустить сервер, нужен sudoers-грант.',
        'local_api_offer': 'Включить приём файлов до 2 ГБ через локальный Bot API сервер? Ответь Да или Нет.',
        'local_api_preparing': '⏳ Готовлю локальный Bot API сервер…',
        'local_api_ready_restarting': '✅ Готово. Перезапускаю бота…',
        'local_api_restart_failed': '⚠️ Не смог перезапустить локальный сервер: {error}',
        'local_api_restart_ineffective': '⚠️ Не смог перезапустить локальный сервер: сервис или его порт не стал активен.',
        'local_api_restart_now': '🔁 Перезапускаю бота, чтобы обновление вступило в силу…',
        'local_api_reuse_existing': '✅ Найден уже настроенный локальный сервер, пересобирать не нужно.',
        'local_api_stage_build': '⏳ Собираю локальный Bot API сервер (может занять ~15 минут)…',
        'local_api_stage_dependencies': '⏳ Проверяю зависимости сборки…',
        'local_api_stage_done': '✅ Локальный сервер собран.',
        'local_api_stage_install': '⏳ Устанавливаю сервис…',
        'local_api_switch_failed': 'Переключатель завершился с кодом {code}',
        'local_api_was_inactive_restarted': '🔧 Локальный сервер был неактивен, перезапустил.',
        'login_complete': '✅ Вход в аккаунт Codex завершён.',
        'login_complete_ask_name': '✅ Вход в аккаунт Codex завершён.\n\nКак к тебе обращаться?',
        'login_complete_first': 'Сначала заверши вход в Codex по ранее выданной ссылке.',
        'login_device_instructions': '🔐 Подключение отдельного аккаунта Codex\n\n1. Открой: {verification_url}\n2. Введи код: {user_code}\n\nТокены сохранятся только в твоём изолированном CODEX_HOME. Бот сообщит, когда вход завершится.',
        'login_failed': '❌ Вход не завершён: {error}',
        'login_owner_not_needed': 'Владелец использует основной аккаунт ~/.codex; отдельный вход не требуется.',
        'login_start_error': 'Не удалось начать вход в Codex: {error}',
        'login_unknown_error': 'неизвестная ошибка',
        'mode_usage': 'Использование: /mode read-only|workspace-write|full',
        'model_empty': 'Codex не вернул доступных моделей.',
        'model_list_error': 'Не удалось получить список моделей: {error}',
        'model_picker_empty': 'Список моделей пуст.',
        'model_picker_header': '🧠 Доступные модели:',
        'model_selected': '🧠 Модель: {model}\nМощность: {effort}',
        'model_unavailable': 'Модель «{model}» недоступна.\n\n{picker}',
        'name_remembered': '✅ Запомнил, как к тебе обращаться.',
        'new_previous_turn_finishing': 'Предыдущий ход ещё завершается; /new пока не выполнен.',
        'new_thread_reset': '🆕 Текущий Codex-тред сброшен. Следующее сообщение начнёт новый.',
        'persona_current_caption': 'Текущая персона',
        'process_agent_default_tool': 'работа агента',
        'process_agent_label': '🤖 Агент · {tool}',
        'process_agent_message_label': '💬 Ответ',
        'process_bash_label': '🔧 Bash',
        'process_context_compaction_done': 'контекст сессии сжат',
        'process_context_compaction_label': '🗜 Сжатие контекста',
        'process_dynamic_tool_default_name': 'инструмент',
        'process_error_label': '❌ Ошибка',
        'process_exit_code_fail': '❌ Код завершения',
        'process_exit_code_ok': '✅ Код завершения',
        'process_file_change_add': 'создан',
        'process_file_change_delete': 'удалён',
        'process_file_change_fallback': 'файл изменён',
        'process_file_change_label': '📝 Изменение файла',
        'process_file_change_update': 'изменён',
        'process_image_fallback': 'изображение',
        'process_image_generation_in_progress': 'изображение создаётся',
        'process_image_generation_label': '🎨 Генерация изображения',
        'process_image_view_label': '🖼 Просмотр изображения',
        'process_plan_fallback': 'план обновлён',
        'process_plan_label': '📋 План',
        'process_reasoning_label': '🧠 Размышление',
        'process_result_generic': 'результат получен',
        'process_result_label': '📤 Результат',
        'process_review_entered': 'режим проверки включён',
        'process_review_exited': 'режим проверки завершён',
        'process_review_label': '🔍 Проверка',
        'process_sleep_label': '⏳ Ожидание',
        'process_sleep_seconds': '{seconds} с',
        'process_tool_label': '🔧 {name}',
        'process_unknown_label': '🔧 Инструмент',
        'process_web_search_default_query': 'поиск',
        'process_web_search_find_in_page': 'ищу на странице',
        'process_web_search_label': '🔎 Поиск',
        'process_web_search_open_page': 'открываю страницу',
        'process_web_search_searching': 'ищу в интернете',
        'process_details_block': '<details><summary>🔧 Процесс ({count})</summary>\n{body}\n</details>',
        'process_hidden_steps': '…и ещё {hidden} шагов выше…',
        'thinking_placeholder': 'Думаю',
        'turn_codex_error': '⚠️ Ошибка Codex: {error}',
        'turn_delegation_footer': '\n\nПродолжить делегированную сессию: `/resume {thread_id}`',
        'turn_delegation_footer_with_prior': '\n\nТвой session id (до делегации): `{prior_thread_id}`. Продолжить делегированную: `/resume {thread_id}`',
        'turn_no_answer': '(нет ответа — смотри процесс выше)',
        'turn_stopped': '⏹ Выполнение остановлено.',
        'turn_tokens_line': '\n\nТокены: {usage}',
        'persona_empty': 'Пустая персона не сохранена.',
        'persona_file_read_error': 'Не удалось прочитать файл персоны: {error}',
        'persona_file_type_error': 'Файл персоны должен быть текстовым UTF-8 Markdown-файлом.',
        'persona_owner_only': 'Персона доступна только владельцу в личном чате.',
        'persona_reply_prompt': 'Пришли текст персоны или UTF-8 Markdown-файл ответом на сообщение.',
        'persona_reset_done': '✅ Персона сброшена к шаблону по умолчанию.',
        'persona_updated': '✅ Персона обновлена.',
        'persona_usage': 'Использование: /persona или /persona reset',
        'restart_after_turn': '🔄 Текущий ход завершён. Перезапускаю Codex-бота…',
        'restart_complete': '✅ Перезагрузка окончена, бот готов к работе.',
        'restart_in_progress': '🔄 Уже начинаю перезапуск; сообщение пока не принято.',
        'restart_owner_only': 'Перезапуск доступен только владельцу бота.',
        'resume_ambiguous': 'Укажи однозначный id/префикс: /resume <id>',
        'resume_delegated_kind': 'делегированную ',
        'resume_not_found': 'Сессия не найдена.',
        'resume_previous_turn_finishing': 'Предыдущий ход ещё завершается; /resume пока не выполнен.',
        'resume_success': 'Продолжаю {kind}сессию {thread_id}.',
        'session_budget_exceeded': 'Бюджет этой сессии исчерпан. Начни новую через /new.',
        'session_missing_new_started': 'Прежняя сессия не найдена; начата новая сессия Codex.',
        'sessions_current_marker': ' ← текущая',
        'sessions_list': 'Последние сессии:\n{rows}',
        'sessions_none': 'не найдены',
        'status_account_unlinked': 'не подключён',
        'status_no': 'нет',
        'status_no_session': 'нет',
        'status_report': 'ℹ️ Статус\nСессия: {thread_id}\nМодель: {model}\nМощность: {effort}\nSandbox: {sandbox}\nWorkspace: {workspace}\nЗанят: {busy}\nАккаунт: {account_status}',
        'status_unknown': 'не определена',
        'status_yes': 'да',
        'stop_idle': 'Сейчас нечего останавливать.',
        'stop_running': '⏹ Останавливаю текущее выполнение Codex.',
        'update_failed': '❌ Обновление не удалось:\n```\n{error}\n```',
        'update_owner_only': 'Обновление доступно только владельцу бота.',
        'update_restart_after_turn': '✅ {summary}{suffix}\n🔁 Перезапуск запланирован после завершения текущего хода.',
        'update_restart_between_turns': '✅ {summary}{suffix}\n🔁 Перезапуск запланирован между ходами.',
        'update_done_default_summary': 'Обновление завершено.',
        'update_script_failed': 'update.sh завершился с кодом {code}',
        'update_start': '⬇️ Обновляю из git...',
        'update_summary_line': '✅ {summary}',
        'rate_limit_line': '{label}: использовано {used}% · осталось {remaining}% · сброс {reset}',
        'rate_limit_no_data': '{label}: нет данных',
        'relative_time_days_hours': 'через {days} д {hours} ч',
        'relative_time_hours_minutes': 'через {hours} ч {minutes} мин',
        'relative_time_minutes': 'через {value} мин',
        'usage_context_line': 'Context: {context}',
        'usage_context_tokens': '~{tokens} tokens',
        'usage_cost_api_equivalent': '(~${usd} эквивалент по API-тарифу)',
        'usage_cost_error': 'Стоимость: не удалось получить ({error})',
        'usage_cost_unavailable': 'Стоимость: недоступна для текущего subscription-маршрута',
        'usage_credits_line': 'Credits: {balance}',
        'usage_effort_unknown': 'не определён',
        'usage_label_cached': 'cached',
        'usage_label_in': 'in',
        'usage_label_out': 'out',
        'usage_label_reasoning': 'reasoning',
        'usage_limit_exceeded_details': '⏳ Лимит сессии Codex исчерпан: {details}. После сброса можно продолжить этот же тред.',
        'usage_limit_exceeded_generic': 'Лимит сессии Codex исчерпан. Попробуй позже; актуальное состояние — /usage.',
        'usage_limits_failed': 'Не удалось получить: {error}',
        'usage_limits_header': '📈 Account limits (subscription, not credits)',
        'usage_messages_line': 'Messages: {messages}',
        'usage_no_active_session': 'нет активной',
        'usage_no_data': 'нет данных',
        'usage_plan_line': 'Plan: {plan}',
        'usage_session_header': '📊 Session',
        'usage_session_line': '{thread_id}  •  Model: {model}  •  Effort: {effort}',
        'usage_tokens_header': '🔢 Tokens (this session)',
        'usage_tokens_line': 'in {input_tokens}  ·  out {output_tokens}  ·  cache-r {cache_read}  ·  cache-w {cache_write}',
        'usage_window_5h': '5-часовой лимит',
        'usage_window_reset': '{label}, сброс {reset}',
        'usage_window_weekly': 'недельный лимит',
        'workspace_missing': 'Директория не существует: {path}',
        'workspace_usage': 'Workspace: {workspace}\nИспользование: /workspace <путь>|default',
    },
    "en": {},
    "uk": {},
    "kk": {},
    "de": {},
}


def t(key, lang=None, **kwargs) -> str:
    lang = lang or current_language.get()
    template = STRINGS.get(lang, {}).get(key)
    if template is None:
        template = STRINGS["ru"][key]
    return template.format(**kwargs)
